Allow shelldb to detect its settings from argv and document it.
fedora-infra/bodhi pull request #1022
Opened 2016-10-11 21:12 UTC by bowlofeggs

This commit adjusts the small shelldb.py utility to be a little
more flexible and allow it to detect which settings files should be
used by inspecting sys.argv for any arguments that end in .ini.
Though this is a "simpleton" approach and normally I'd want
something more robust, it does work and this is just a development
tool.

2016-10-12 10:04 UTC, pypingou commented
:+1: for me

2016-10-12 11:20 UTC, sayanchowdhury requested changes

2016-10-12 11:20 UTC, sayanchowdhury commented on tools/shelldb.py
> +    if '.ini' in arg:
Better to check `arg.endswith('.ini')`

2016-10-18 20:32 UTC, bowlofeggs commented
@sayanchowdhury I've made the change you requested.

2016-10-19 08:03 UTC, pypingou commented
Still :+1: for me

2016-10-26 02:09 UTC, sayanchowdhury commented
:+1:

2016-11-02 22:57 UTC, merged