Add check-sig-status argument to bodhi-push
fedora-infra/bodhi pull request #1088
Opened 2016-11-05 19:52 UTC by puiterwijk

This argument makes the push command check out to koji to refresh the
signed state of builds if requested.
This handles the case where for some reason the signed handler didn't pick
up on the signed status update, and admins really want to check it.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2016-11-11 16:51 UTC, bowlofeggs commented on bodhi/server/push.py
>  import bodhi.server.notifications
Very small nitpick, but I find alphabetic sorting of the imports to be pleasing ☺

2016-11-11 16:55 UTC, bowlofeggs requested changes
Before we merge this, we'll need two changes:
1. We need tests for the new code.
2. Let's move the new code into its own helper function.

2016-11-11 16:55 UTC, bowlofeggs commented on bodhi/server/push.py
> +                                build.signed = True
This function is pretty large as it is and should be refactored to use sub functions so it's cleaner. Can we make the above code block be a helper function instead? We can refactor the rest of this method as a separate effort.

2016-12-20 20:03 UTC, bowlofeggs commented
@puiterwijk This pull request has been sitting with requested changes for a while. Do you still intend to work on it?

2016-12-21 00:27 UTC, puiterwijk commented
@bowlofeggs no, as I told you a while ago I think that since we now have the root cause of the issue fixed, this can be closed.
Howver, you still wanted this code to go in, so closing is up to you.

2016-12-21 21:06 UTC, closed without merging