removed from models import* from bodhi.server.models.__init__
fedora-infra/bodhi pull request #1100
Opened 2016-11-12 09:42 UTC by ankit01ojha

removed the pacjkage bodhi.server.models and replaced it with bodhi.server.models.py.

2016-11-12 09:43 UTC, ankit01ojha commented
Sorry for four commits, I'am new to github :(

2016-11-12 10:24 UTC, trishnaguha requested changes

2016-11-12 10:24 UTC, trishnaguha commented on bodhi/server/models.py
> +from bodhi.server.models import models
We don't really need this inside  `models.py`

2016-11-12 10:26 UTC, trishnaguha commented
Could you move all the import statements to the top? https://github.com/ankit01ojha/bodhi/blob/develop/bodhi/server/models.py#L159-L205

2016-11-12 10:28 UTC, trishnaguha commented
We don't need to import from `enum` anymore since it is inside `models.py` now https://github.com/ankit01ojha/bodhi/blob/develop/bodhi/server/models.py#L196

2016-11-12 10:29 UTC, trishnaguha commented
Please fix the branch conflict.

2016-11-12 10:30 UTC, trishnaguha commented
@ankit01ojha Did you run the test suite? If not can you please run the test suite? Because I think some of the tests are going to fail because of the import :).

2016-11-12 12:32 UTC, ankit01ojha commented
Thanks @trishnaguha  i'll correct them.

2016-11-13 03:44 UTC, trishnaguha requested changes

2016-11-13 03:44 UTC, trishnaguha commented on bodhi/server/models.py
> +from sqlalchemy.types import SchemaType, TypeDecorator, Enum
The idea is to keep all the import statements together. https://github.com/ankit01ojha/bodhi/blob/b7fdff2e6f66d8a487848f8424189bec798a55c9/bodhi/server/models.py#L1-L83
Please check the import guide https://www.python.org/dev/peps/pep-0008/#imports

2016-11-13 03:46 UTC, trishnaguha requested changes

2016-11-13 03:46 UTC, trishnaguha commented on bodhi/server/models.py
> +# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
Move the docstring before import statement https://www.python.org/dev/peps/pep-0008/#imports
Here is  duplication of docstring https://github.com/ankit01ojha/bodhi/blob/b7fdff2e6f66d8a487848f8424189bec798a55c9/bodhi/server/models.py#L49-L77

2016-11-13 09:18 UTC, trishnaguha requested changes

2016-11-13 09:18 UTC, trishnaguha commented on bodhi/server/models.py
> +import re
Importing `re` module twice?

2016-11-13 09:20 UTC, trishnaguha requested changes

2016-11-13 09:20 UTC, trishnaguha commented on bodhi/server/models.py
> +from sqlalchemy.types import SchemaType, TypeDecorator, Enum
Could you move this to https://github.com/ankit01ojha/bodhi/blob/0ce799e298fa85d3f734debd4a5b439a50275a3a/bodhi/server/models.py#L45 ?

2016-11-13 10:30 UTC, ankit01ojha commented on bodhi/server/models.py
> +from sqlalchemy.types import SchemaType, TypeDecorator, Enum
Do I have to write this in place of https://github.com/ankit01ojha/bodhi/blob/0ce799e298fa85d3f734debd4a5b439a50275a3a/bodhi/server/models.py#L45 or before it?

2016-11-14 05:32 UTC, trishnaguha requested changes

2016-11-14 05:32 UTC, trishnaguha commented on bodhi/server/models.py
>  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
There is still duplication here https://github.com/ankit01ojha/bodhi/blob/8f4a951731fc8a2b32439092ae3587a404a3e076/bodhi/server/models.py#L173-L187

2016-11-14 05:33 UTC, trishnaguha requested changes

2016-11-14 05:33 UTC, trishnaguha commented on bodhi/server/models.py
> -# encoding: utf-8
Do not remove `encoding: utf-8` :).

2016-11-14 05:34 UTC, trishnaguha commented
Can you please fix the branch conflict? And squash and rebase your commits before pushing?

2016-11-14 05:38 UTC, trishnaguha requested changes

2016-11-14 05:38 UTC, trishnaguha commented on .gitignore
> +.idea/
It would be more perfect to have `*.idea/*` instead of `.idea/`.

2016-11-14 08:45 UTC, trishnaguha requested changes

2016-11-14 08:45 UTC, trishnaguha commented on bodhi/server/models.py
> +t.impl.drop(bind=bind, checkfirst=checkfirst)
Wrong indentation here.

2016-11-14 11:36 UTC, trishnaguha requested changes

2016-11-14 11:36 UTC, trishnaguha commented on bodhi/server/models.py
>      log.warning("Could not import 'rpm'")
Don't we want to keep the first try block here? https://github.com/ankit01ojha/bodhi/blob/8f4a951731fc8a2b32439092ae3587a404a3e076/bodhi/server/models.py#L28-L32

2016-11-14 12:36 UTC, ankit01ojha commented on bodhi/server/models.py
>      log.warning("Could not import 'rpm'")
Yes, we can.

2016-11-14 15:02 UTC, ankit01ojha commented
Sorry it again went two commits :(

2016-11-14 16:33 UTC, trishnaguha commented on bodhi/server/models.py
>      log.warning("Could not import 'rpm'")
This looks pretty messed up now. This is not what I meant https://github.com/ankit01ojha/bodhi/blob/b416dcbd62073fa3a495dcd9975c096504e92a0b/bodhi/server/models.py#L53-L60

2016-11-14 18:44 UTC, ankit01ojha commented on bodhi/server/models.py
>      log.warning("Could not import 'rpm'")
Should I undo it ?

2016-11-16 10:40 UTC, ankit01ojha commented on bodhi/server/models.py
>      log.warning("Could not import 'rpm'")
If I put the first try block here then can you please tell me where this try block should go:https://github.com/ankit01ojha/bodhi/blob/8f4a951731fc8a2b32439092ae3587a404a3e076/bodhi/server/models.py#L59-L62   ?

2016-11-16 12:20 UTC, trishnaguha commented on bodhi/server/models.py
>      log.warning("Could not import 'rpm'")
We should avoid having `try-block` in the middle of the `import` statements.

2016-12-20 20:04 UTC, bowlofeggs commented
@ankit01ojha This pull request has been sitting for a while. Do you still intend to work on it?

2016-12-23 04:48 UTC, ankit01ojha commented
@bowlofeggs sorry, for keeping this PR still for a while, I was having issues with my laptop that's why I was not able to work. Now its fixed , so i'll work.

2016-12-23 17:34 UTC, closed without merging

2016-12-24 05:03 UTC, ankit01ojha commented
@bowlofeggs I have closed this PR as it looks pretty messed up :) 
A new PR has been opened https://github.com/fedora-infra/bodhi/pull/1190.

2016-12-26 17:59 UTC, bowlofeggs commented
On Fri, 2016-12-23 at 21:03 -0800, Ankit Raj Ojha wrote:
> @bowlofeggs I have closed this PR as it looks pretty messed up :)
> A new PR has been opened #1190.

Hello!

For next time, you can alter history in your own branch and force push
it to update the pull request. This will prevent you from having to
open a new one when you want to make changes.

2016-12-29 06:57 UTC, ankit01ojha commented
@bowlofeggs Thanks, I'll keep that for the next time. :)