Disable caching koji sessions during mashing process
fedora-infra/bodhi pull request #1122
Opened 2016-11-20 20:48 UTC by puiterwijk

The mashing process takes a very long time: longer than the session timeout for the
bodhi user in koji.
Since a koji session is started on buildsys.get_session(), that means the koji session
often times out if the mash takes too long.
This patch makes us get a new session for each batch of koji operations.

This will incur a slight performance impact, but that should not be too big, since most
of the koji operations are batched, and this change gets a new session on each batch.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2016-11-20 20:50 UTC, puiterwijk commented
The traceback that this fixes is:

```
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]: [2016-11-20 20:28:59][    fedmsg   ERROR]epel7 MasherThread failed. Transaction rolled back.                                                               [104/979]
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]: Traceback (most recent call last):
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 259, in run
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self.work()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 338, in work
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     uinfo = self.generate_updateinfo()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 709, in generate_updateinfo
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self.db, self.path)
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 80, in __init__
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self._load_cached_updateinfo()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 143, in _load_cached_updateinfo
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self.add_update(update)
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 227, in add_update
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     rpms = self.koji.listBuildRPMs(kojiBuild['id'])
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1736, in __call__
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     return self.__func(self.__name,args,opts)
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2124, in _callMethod
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self._close_connection()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2055, in _close_connection
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self._connection[1].close()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib64/python2.7/httplib.py", line 848, in close
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     sock.close()   # close it manually... there may be other refs
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/koji/ssl/SSLConnection.py", line 82, in close
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self.shutdown()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/koji/ssl/SSLConnection.py", line 53, in shutdown
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self.__dict__["conn"].shutdown()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1520, in shutdown
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     self._raise_ssl_error(self._ssl, result)
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1191, in _raise_ssl_error
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     _raise_current_error()
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:   File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]:     raise exception_type(errors)
11月 20 20:28:59 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[9762]: Error: [('SSL routines', 'SSL_shutdown', 'shutdown while in init')]

```

2016-11-28 16:01 UTC, bowlofeggs requested changes
We will need tests for this change.

2016-11-28 18:06 UTC, bowlofeggs commented
I will write tests for the first of these commits since it is needed for us to release 2.3.3. Once I have test coverage, I may just cherry pick that one commit and leave the other as an open pull request.

2016-11-28 18:38 UTC, bowlofeggs commented on bodhi/server/buildsys.py
> +        self._check_expiration()
I wonder if we could do something like this (I've not tried this, just an idea):

```
def __getattr__(self, attr):
    self._check_expiration()
    return super(DevBuildSys, self).__getattr__(attr)
```

That way we don't have to add ```self._check_expiration()``` everywhere, and it will also be future proof if anyone ever adds a new method (so they won't have to remember to add that call).

What do you think?

I'm also OK with this change as-is if you prefer not to do that, it's just an idea.

2016-11-29 04:27 UTC, bowlofeggs commented
I've submitted #1134, which has the first of these two commits cherry picked. I suggest that we merge that commit there and leave this PR just to focus on the second commit.

2016-11-29 18:14 UTC, bowlofeggs commented
I'm dropping this PR from the 2.3.3 milestone since #1134 has the commit we need from this PR cherry picked.

2016-12-20 20:06 UTC, bowlofeggs commented
@puiterwijk IMO we probably don't need the remaining commit in this pull request. I think it's unlikely that the tests would trigger the check, and the check adds a lot of repeat calls to the various methods. However, I'm open to it if you really want to get it in. Do you still intend to work on this? It's been sitting for a long time.

2016-12-21 00:25 UTC, puiterwijk commented
Nah, let's just drop it then.

2016-12-21 00:25 UTC, closed without merging