Fail horribly if we forget to setup the build system
fedora-infra/bodhi pull request #1124
Opened 2016-11-20 21:40 UTC by puiterwijk

Currently, if someone forgets to set the buildsys, we will silently (because who
ever sets up logging for "bodhi" if they're working in a shell?).
This commit makes sure that we require people to have setup a buildsys before we
will allow them to get a session.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2016-11-28 16:18 UTC, bowlofeggs requested changes
We need test coverage.

2016-12-20 20:21 UTC, bowlofeggs requested changes
Let's use an Exception instead of an ```assert``` statement.

2016-12-20 20:21 UTC, bowlofeggs commented on bodhi/server/buildsys.py
> +    assert _buildsystem is not None, 'Buildsys needs to be setup'
```assert``` statements get stripped out in .pyo files - it's important to raise an Exception since we want the production code to behave this way.

2016-12-20 20:21 UTC, bowlofeggs commented on bodhi/server/buildsys.py
I suggest dropping this space for readability.

2016-12-21 17:30 UTC, puiterwijk commented on bodhi/server/buildsys.py
Sorry, which space do you mean?

2016-12-21 21:08 UTC, bowlofeggs commented on bodhi/server/buildsys.py
Sorry, I meant "newline", not "space".

2016-12-21 21:27 UTC, bowlofeggs approved these changes
Approved as-is, or you can drop that newline if you want to at your option. Thanks!

2016-12-21 21:30 UTC, merged