Lock the buildsystem while logging in
fedora-infra/bodhi pull request #1142
Opened 2016-12-02 18:02 UTC by puiterwijk

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2016-12-09 17:47 UTC, bowlofeggs commented
@puiterwijk Why do we want to do this? Also, this will need tests.

2016-12-14 18:15 UTC, puiterwijk commented
Because having two sessions that login at the exact same moment confuses koji.

2016-12-14 18:26 UTC, bowlofeggs commented
@puiterwijk Bodhi does have multiple processes, though I'm not sure which of them use the buildsys module. Also, I'm not sure how we have httpd configured in production (does it use processes and threads… just threads… just processes?) Since this commit only uses thread locking, should we be concerned about the processes causing this confusion?

2016-12-14 18:32 UTC, puiterwijk commented
The problematic part is the mash stuff. It uses multiple threads, and LOTS of calls to the buildsystem, so LOTS of chances to hit the race condition.
HTTPD side is not a problem.

2016-12-20 20:40 UTC, bowlofeggs requested changes
This needs tests.

2017-01-18 18:40 UTC, jeremycline commented
We obviously need to get this into Bodhi for now, but it seems like upstream Koji would benefit from making the login function thread-safe. Do you know if there's an issue or PR for that? I don't see either, but that doesn't mean it doesn't exist, of course.

2017-01-18 18:57 UTC, bowlofeggs commented
On Wed, 2017-01-18 at 10:40 -0800, Jeremy Cline wrote:
> We obviously need to get this into Bodhi for now, but it seems like
> upstream Koji would benefit from making the login function thread-
> safe. Do you know if there's an issue or PR for that? I don't see
> either, but that doesn't mean it doesn't exist, of course.

I'm not sure, but I'm a huge +1 to the suggestion of sending this to
Koji. We can keep this code for now until they have it.

2017-01-18 18:59 UTC, jeremycline commented on bodhi/server/buildsys.py
> +    _buildsystem_login_lock = Lock()
Out of curiosity, why not just initialize this at the module level rather than involving ``global`` and a function?

2017-01-19 04:21 UTC, puiterwijk commented on bodhi/server/buildsys.py
> +    _buildsystem_login_lock = Lock()
To be consistent with the rest of the code.

2017-01-19 22:00 UTC, jeremycline commented on bodhi/server/buildsys.py
> +    _buildsystem_login_lock = Lock()
Okay, cool. I'm inclined to change it to initialize at the module level since that's less surprising to me.

2017-01-19 22:06 UTC, jeremycline commented
I added unit tests on top of this commit in #1230 and had my question answered here so I'm going to go ahead and close this.

2017-01-19 22:06 UTC, closed without merging