Removed the traceback  #Fixed 1126
fedora-infra/bodhi pull request #1211
Opened 2017-01-07 16:09 UTC by ankit01ojha

Removed the traceback and printed a message instead of it.

2017-01-09 16:46 UTC, ankit01ojha commented
@bowlofeggs Is this ok :)

2017-01-09 16:56 UTC, jeremycline commented
Hi @ankit01ojha, thanks for the contribution!

In this case, I think it's appropriate to print the traceback, since it's a general ``Exception`` block. Is there an issue associated with this pull request?

2017-01-09 16:59 UTC, ankit01ojha commented
@jeremycline yes, there it is https://github.com/fedora-infra/bodhi/issues/1126

2017-01-09 17:03 UTC, bowlofeggs commented
@ankit01ojha Can you move the "Fixed 1126" out of the subject line and into the commit message body? Also, I think GitHub expects it to be "fixes" instead of "Fixed". So a good commit message would be:

```
Do not traceback when CLI users enter the wrong password.

fixes #1126
```

This way GitHub will automatically close #1126 when the commit is merged.

2017-01-09 17:08 UTC, ankit01ojha commented
@bowlofeggs Thanks :)

2017-01-09 17:14 UTC, jeremycline requested changes
I think a better approach is to add an ``except`` block for the specific exception raised on authentication failure. According to the issue, that's ``fedora.client.AuthError``

2017-01-09 17:14 UTC, jeremycline commented on bodhi/client/__init__.py
> -            traceback.print_exc()
I think we should keep this except block as it is since it's a general (unexpected) exception and that means it's a bug.

2017-01-09 17:14 UTC, jeremycline commented on bodhi/client/__init__.py
> +	    print("Wrong password, Try again")
The indentation is not a multiple of 4 here

2017-01-09 22:20 UTC, bowlofeggs requested changes
I agree with @jeremycline, we want to keep the except block the way it is and add a new handler for the authentication exception.

Additionally, we need tests for this change.

2017-01-09 22:20 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +	    print("Wrong password, Try again")
Let's use the click library for I/O instead of print statements, as it makes testing easier.

2017-01-17 11:55 UTC, ankit01ojha commented on bodhi/client/__init__.py
> +	    print("Wrong password, Try again")
@bowlofeggs I'am trying to make it as you both suggested. :)

2017-01-20 18:44 UTC, ankit01ojha commented
@bowlofeggs I tried to work on it but I am not able to figure out how I do this, could you just help me bit .

2017-01-22 10:17 UTC, closed without merging