Changed the position of Add Comment button #fixes 1216
fedora-infra/bodhi pull request #1227
Opened 2017-01-16 14:17 UTC by ankit01ojha

Changed the position of Add Comment from the bottom right to just right-side below the solution field.

2017-01-16 14:18 UTC, ankit01ojha commented
@trishnaguha can you review it :)

2017-01-17 16:07 UTC, trishnaguha commented
@ankit01ojha Can you attach screenshot of the page since it is related to UI?

2017-01-18 13:35 UTC, ankit01ojha commented
![screenshot from 2017-01-18 19-05-19](https://cloud.githubusercontent.com/assets/21126132/22066053/14d7b758-ddb1-11e6-9583-acbd7d1846e8.png)

2017-01-18 13:36 UTC, ankit01ojha commented
@trishnaguha Is this fine?

2017-01-18 13:38 UTC, trishnaguha commented
It would look better if you can align the button to right :) ? just like where the text-boxes end?

2017-01-18 13:57 UTC, ankit01ojha commented
![screenshot from 2017-01-18 19-23-55](https://cloud.githubusercontent.com/assets/21126132/22066697/29de474a-ddb4-11e6-8760-7b18a4350957.png)

2017-01-18 13:58 UTC, ankit01ojha commented
@trishnaguha I think it looks good here :)

2017-01-18 18:28 UTC, bowlofeggs commented
@ankit01ojha It still looks a little too far to the right, and it's also bumped up against the Solution answer box. We probably want it to have a little space. @ryanlerch is the UX x-pert though. Ryan, what do you think?

Additionally, we should also make sure this looks nice on mobile. The button actually looks perfect on mobile as-is with no changes, IMO:

![screenshot_20170118-090202](https://cloud.githubusercontent.com/assets/354506/22077360/e3dc639e-dd81-11e6-9cdb-2f282d634032.png)

So let's make sure that any changes we make continue to look good in a mobile browser.

2017-01-19 02:30 UTC, trishnaguha commented
@bowlofeggs Since the **Add Comment** button is below the `Feedback Guidelines`, when the number `Test Case` grows the button goes more down.. appears right after the last testcase :).
For instance this one: https://bodhi.fedoraproject.org/updates/FEDORA-2016-788a7edfd7

2017-01-19 15:54 UTC, ankit01ojha commented
![screenshot from 2017-01-19 21-16-14](https://cloud.githubusercontent.com/assets/21126132/22113844/a15c35fa-de8d-11e6-8d01-a5b389a4f5e0.png)

2017-01-19 15:55 UTC, ankit01ojha commented
@trishnaguha and @bowlofeggs I hope this is as required :)

2017-01-19 16:07 UTC, trishnaguha commented
LGTM :+1:

2017-01-19 16:35 UTC, ankit01ojha commented
@trishnaguha can it be merged?

2017-01-20 16:47 UTC, ankit01ojha commented
@bowlofeggs Is this fine?

2017-01-23 16:02 UTC, bowlofeggs commented
This does look nice on my desktop now, I tested that same update the @trishnaguha linked with a development checkout of this PR: http://localhost:6543/updates/FEDORA-2016-788a7edfd7

However, when I view this PR on my phone, the button is presented before the karma choices:

![screenshot_20170123-105841](https://cloud.githubusercontent.com/assets/354506/22211518/4035f3b2-e15b-11e6-9470-6d808eda05a9.png)

I think we'd ideally want to find a way to keep the button below the karma prompts on mobile, while having it look similar to how it looks on desktop in your pull request.

I'm not an HTML guru. Ideas?

2017-01-24 13:47 UTC, ankit01ojha commented
@bowlofeggs This might work, I have changed the visibility of add comment button. When it will be in mobile size add comment will appear as you want  and as when its in large size(desktop or more) it will come as I have pasted in my screenshot.

2017-02-02 17:26 UTC, bowlofeggs requested changes

2017-02-02 17:26 UTC, bowlofeggs commented on bodhi/server/templates/update.html
> +          </div>
I don't think we want to duplicate code like this. Let's see if we can find a solution that doesn't repeat this block.

2017-02-02 17:43 UTC, ankit01ojha commented on bodhi/server/templates/update.html
> +          </div>
I will be searching for it also, but can it be merged untill its new solution is found :)

2017-02-02 19:06 UTC, bowlofeggs commented
On Thu, 2017-02-02 at 09:43 -0800, Ankit Raj Ojha wrote:
> I will be searching for it also, but can it be merged untill its new
> solution is found :)

I would prefer not to make a change until we have the right change. As
it is, the code is relatively simple and the button mostly works. This
proposed change will raise the complexity of the code and will violate
the DRY principle:

https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

In other words, the issue isn't severe enough to warrant workaround-
type changes to our code.

2017-03-02 17:11 UTC, bowlofeggs commented
I believe this issue is addressed by #1313, so I am closing this pull request.

2017-03-02 17:11 UTC, closed without merging