Specify clone directory for comps file
fedora-infra/bodhi pull request #1231
Opened 2017-01-19 02:42 UTC by puiterwijk

Otherwise if the upstream repo changes names it gets cloned into another
directory.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2017-01-20 16:43 UTC, jeremycline commented
@bowlofeggs I added tests for this change. I also adjusted the method a bit to make a test pass, but I can adjust things if you don't want that change as part of this.

2017-01-23 16:21 UTC, bowlofeggs requested changes
Let's add an assertion on the arguments to ```os.path.exists``` and also add a test to assert correct behavior when the path does exist.

2017-01-23 16:21 UTC, bowlofeggs commented on bodhi/tests/server/consumers/test_masher.py
> +        self.assertEqual(calls, mock_cmd.call_args_list)
We should add one more test like this one that tests for when ```os.path.exists``` return True. Also, it'd be good to assert that ```os.path.exists()``` was called with the correct path here and in the new test.

2017-01-25 15:26 UTC, jeremycline commented on bodhi/tests/server/consumers/test_masher.py
> +        self.assertEqual(calls, mock_cmd.call_args_list)
Done

2017-02-02 17:40 UTC, bowlofeggs approved these changes
Yes, we are inching towards a release!

2017-02-02 17:40 UTC, merged