Removed from models import* #fixed 1057
fedora-infra/bodhi pull request #1233
Opened 2017-01-21 13:24 UTC by ankit01ojha

Replaced `bodhi.server.models` package to `bodhi.server.models` module.

2017-01-23 11:14 UTC, ankit01ojha commented
@bowlofeggs can you please review this :)

2017-01-23 12:48 UTC, trishnaguha commented
@ankit01ojha Looks like you already opened several PRs for this issue before. When modifying commit it is recommended to do force push instead of closing the PR and opening a new one.

2017-01-23 13:18 UTC, ankit01ojha commented
@trishnaguha  I am really sorry for this this won't happen again( I was new to github, now I quite used to it).

2017-01-23 16:26 UTC, bowlofeggs requested changes
We don't want to make changes that are unrelated to renaming the module. Also, the tests do not pass.

2017-01-23 16:26 UTC, bowlofeggs commented on bodhi/server/models.py
> +from sqlalchemy import DateTime
We shouldn't be making very many modifications to this file, other than merging the Enum items in. This import is needed, and I see a lot of other unrelated changes elsewhere in the file.

2017-01-24 14:31 UTC, ankit01ojha commented
@bowlofeggs I corrected all the unrelated changes.

2017-02-02 17:54 UTC, bowlofeggs commented on bodhi/server/models.py
> -
Dropping all of these spaces are not related to the change - can you make sure that only the ```git mv``` and merging enum in are happening in this pull request?

2017-02-03 13:45 UTC, ankit01ojha commented
@bowlofeggs Is this fine now or still needs some improvement?

2017-02-03 15:03 UTC, ankit01ojha commented
@bowlofeggs Is this fine or it still needs corrections?

2017-02-03 15:21 UTC, trishnaguha commented
@ankit01ojha Can you run the testsuite with these changes and update the ticket with the result of your test (Result as in Success or Failing). That's the best way which lets you know if you are doing it right when dealing with large codebase. 
To run the testsuite follow the Doc: https://github.com/fedora-infra/bodhi/blob/develop/docs/developer_docs.rst#quick-tips-about-the-bodhi-vagrant-environment

2017-02-05 06:01 UTC, ankit01ojha commented
@trishnaguha I tried to do this https://github.com/fedora-infra/bodhi/blob/develop/docs/developer_docs.rst#quick-tips-about-the-bodhi-vagrant-environment as you said but I can't find anything in my in .bashrc so ran the `$ nosetests -v` here's the output all tests passed .

![screenshot from 2017-02-05 11-30-54](https://cloud.githubusercontent.com/assets/21126132/22624058/a7641f38-eb96-11e6-8f6d-994dcc1323f4.png)

2017-02-05 06:15 UTC, ankit01ojha commented
@trishnaguha @trishnaguha I tried to do this https://github.com/fedora-infra/bodhi/blob/develop/docs/developer_docs.rst#quick-tips-about-the-bodhi-vagrant-environment as you said but I can't find set of commands in your `.bashrc` so ran the `$ nosetests -v` here's the output.

![screenshot from 2017-02-05 11-42-52](https://cloud.githubusercontent.com/assets/21126132/22624156/9fc2d722-eb98-11e6-99b1-3434dbbc1a03.png)

2017-02-06 13:46 UTC, ankit01ojha commented
I am confused does it need changes, as error shown are the files that I have removed.

2017-02-06 18:46 UTC, bowlofeggs commented
I am guessing that the old ```.pyc``` file ```__init__.pyc``` may still be present on your system.

2017-02-07 08:24 UTC, ankit01ojha commented
@bowlofeggs this time it passed 79% other errors are coming due to the import of `bodhi.server.models` and its files, so, do I have to make changes in all other file in this commit or I make other commit for them?
![screenshot from 2017-02-07 13-53-39](https://cloud.githubusercontent.com/assets/21126132/22683213/dec314d2-ed3c-11e6-9be6-683140a3dc97.png)

2017-02-07 08:26 UTC, ankit01ojha commented
@bowlofeggs After removing the old `.pyc` files and making some corrections I ran the test and it passed 79%, other errors are due to the other files which are importing models.
![screenshot from 2017-02-07 13-53-39](https://cloud.githubusercontent.com/assets/21126132/22683264/2b1a1ede-ed3d-11e6-99cb-a72a6cb8a9d5.png)

2017-02-07 08:57 UTC, trishnaguha commented
@ankit01ojha Can you please paste the failed tests in `fpaste`?

2017-02-07 13:49 UTC, ankit01ojha commented
@trishnaguha Here's it is  https://da.gd/1ccA

2017-02-09 13:36 UTC, bowlofeggs commented
@ankit01ojha The issue is that there are many places in the code that import the file that has been deleted, so you will need to adjust the imports so they import the new location. I recommend going through a Python tutorial or two to learn more about modules and import statements. The official Python 2 tutorial is decent, and it has a page about modules:

https://docs.python.org/2/tutorial/index.html
https://docs.python.org/2/tutorial/modules.html

2017-02-11 18:40 UTC, ankit01ojha commented
@bowlofeggs I almost fixed all the import errors, now its 81% passed which is the minimum required.
The rest errors are https://da.gd/CeOkT. Tried to fix them but was not successful.
![screenshot from 2017-02-12 00-07-04](https://cloud.githubusercontent.com/assets/21126132/22856457/a38cf62a-f0b7-11e6-9cbf-464b336e09ec.png)

2017-02-13 05:43 UTC, trishnaguha commented
@ankit01ojha You need to follow the documentation that bowlofeggs suggested and fix import path. If you can look in to the failed testcases in the fpaste, it gives you hints exactly where your code is failing.

2017-02-13 21:20 UTC, bowlofeggs commented
@ankit01ojha It looks like there are mock statements that are altering the module you've removed. You should be able to look in the cited test files and find those paths. They're often going to be in statements that look like ```@patch('bodhi.server.models.models.') over the tests, but they can also appear inside of tests or start with ```@mock.patch```.

You can read more about mock here:

http://www.voidspace.org.uk/python/mock/

2017-02-15 11:42 UTC, ankit01ojha commented
Thanks @bowlofeggs and @trishnaguha , now it passed all the test .
![screenshot from 2017-02-15 17-07-12](https://cloud.githubusercontent.com/assets/21126132/22972943/e8163134-f3a1-11e6-9ba6-2d27757b20ea.png)

2017-02-17 17:39 UTC, bowlofeggs approved these changes
Nice, this seems to work!

2017-02-17 17:39 UTC, merged

2017-02-17 17:51 UTC, bowlofeggs commented
There were three comments left that referenced the old location, so opted to just fix those in a separate PR: https://github.com/fedora-infra/bodhi/pull/1293