masher should clean up old mashers at the end of every run
fedora-infra/bodhi pull request #1312
Opened 2017-02-25 10:24 UTC by ankit01ojha

fixes #https://github.com/fedora-infra/bodhi/issues/1304

2017-03-02 14:57 UTC, ankit01ojha commented
@bowlofeggs Can you please review this.

2017-03-02 15:13 UTC, bowlofeggs requested changes
I recommend adjusting the commit message to say "mashes" instead of "mashers". Also, the commit message has two #'s in front of the issue number instead of one.

2017-03-02 15:13 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +            print d
This code is duplicated with the script. We don't want to copy code as that violates the DRY Principle:

https://en.wikipedia.org/wiki/Don't_repeat_yourself

Instead, we want to import the existing code that does this and use it from the masher.

2017-03-02 15:13 UTC, bowlofeggs commented on bodhi/tests/server/consumers/test_masher.py
> +            shutil.rmtree(mash_dir)
This test is copied from the existing test. We don't need to retest that this code works, but we do need to assert that the masher calls it when done.

2017-03-10 13:13 UTC, ankit01ojha commented
@bowlofeggs I don't know why but the clean_up function is not getting called, I am getting the test failed `AssertionError: 0 != 1`.

2017-03-14 18:49 UTC, bowlofeggs commented
@ankit01ojha it's not getting called because nothing is explicitly calling it. Python doesn't run functions when they are defined; it runs them when they are called, i.e., you put ```()```'s after its name.

2017-03-14 18:50 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +    pass
I dont' think we need a new function here. We just need to call ```clean_old_mashes()``` when the mash is done and successful.

2017-03-23 17:26 UTC, bowlofeggs commented
This will also need release notes added at https://github.com/fedora-infra/bodhi/blob/develop/docs/release_notes.rst

2017-03-24 15:11 UTC, ankit01ojha commented
done!

2017-03-24 19:23 UTC, bowlofeggs requested changes
This can

2017-03-24 19:23 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +        pass
This method doesn't do anything. Why put it here?

2017-03-24 19:23 UTC, bowlofeggs commented on bodhi/tests/server/consumers/test_masher.py
> +        self.assertEquals(len(clean_up.call_args_list), 1)
This test doesn't run the code and doesn't assert that the clean up call was made.

2017-05-01 12:46 UTC, closed without merging