Added about bodhi and some related links
fedora-infra/bodhi pull request #1333
Opened 2017-03-06 16:15 UTC by ankit01ojha

Added what is bodhi, its advantages and added some related links.

2017-03-07 12:22 UTC, ankit01ojha commented
@bowlofeggs Is this fine, or anything else need to be added.

2017-03-07 14:56 UTC, bowlofeggs requested changes

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +--------------
I think we can drop this heading and just let the paragraph below stand on its own.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +Bodhi is a modular web-based system that facilitates the process of publishing package updates for Fedora. Bodhi is the application that manages updates for Fedora releases. It maintains a single sta
When you say that Bodhi is modular, what do you mean? I haven't thought of it as being modular before.

The first and second sentence seem a little redundant.

What does it mean that Bodhi maintains a single stage of repositories?

I think we can go for something a little simpler here. Perhaps something like "Bodhi is designed to democratize the package update testing and release process for RPM based Linux distributions. It provides an interface for developers to propose updates to a distribution, and an interface for testers to leave feedback about updates through a +1/-1 karma system."

Also, let's try to keep line lengths no longer than 100 columns.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +2.  Helps in delivering quality packages and repository sustainment with automated testing.
What do you mean by sustainment?

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +3.  Helps Community testers to get involved in testing of the package updates and provide quality feedback which would reach the packagers/developers.
I'd probably reword the above a bit. Something like:

"Gives community testers an interface to leave feedback about package updates."

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +1.  Provides an intuitive interface for developers and release engineers to manage pushing out package updates for multiple version releases.
I don't think we need to say it's intuitive - keeping the prose short and to the point makes it more readable. Keep in mind that many people reading the home page of a project are going to be quickly skimming it to find out what it is, so we want to be as direct as possible. We don't need to try to convince them to use Bodhi, we just need to inform them what Bodhi is.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +4.  Provides a modular framework that will allow future integrations to various other QA and developer tools.
I'm not sure that Bodhi is modular.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +5.  Announces the arrival of New packages entering the collection.
s/New/new/

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +6.  The reasons for an update can be communicated to end users.
"Bodhi publishes end-user release notes known as errata."

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +7.  Generates extended update metadata which is parsed client-side by yum.
I'd probably word this more generally. Something like "Generates yum repositories."

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +8.  Allows security updates to be seen by users as a separate channel, with links to the security advisories.
What do you mean by separate channel? The RSS feed? That security updates can be searched in Bodhi?

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +9.  Accomodates automated testing for updates before the latter are released.
Bodhi doesn't actually do any automated testing - it displays automated test results that it retrieves from ResultsDB. I'd probably reword the above:

"Queries ResultsDB for automated test results and displays them on updates."

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +10. Provides pre-release test updates for end users and QA folks who wish to test these updates.
I'd probably s/end users and QA folks/users/.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +For getting a Bodhi development environment you can refer `here <https://pypi.python.org/pypi/bodhi-client/2.3.3>`_
We already have this documented in the README and in this Sphinx project. I don't think the docs home page should repeat this information.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +You can checkout `bodhi's deployment <https://bodhi.stg.fedoraproject.org/>`_
This is the staging deployment, not the real deployment.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +-------------------
I would probably rename this section "Features". Also, I recommend using bullet points instead of numbers below.

2017-03-07 14:56 UTC, bowlofeggs commented on docs/index.rst
> +For `reporting issues <https://github.com/fedora-infra/bodhi/issues>`_ , Click on the New Issue button and create a issue.
How about we just make a "Links" section with common links? Something like this:

```
Links
^^^^^

* `Online documentation <http://bodhi.readthedocs.io>`_
* `Report an issue <https://github.com/fedora-infra/bodhi/issues/new>`_
* `Source code <https://github.com/fedora-infra/bodhi>`_
* `Fedora's production instance <https://bodhi.stg.fedoraproject.org/>`_
* `Fedora's staging instance <https://bodhi.stg.fedoraproject.org/>`_
```

2017-03-08 15:02 UTC, ankit01ojha commented on docs/index.rst
> +2.  Helps in delivering quality packages and repository sustainment with automated testing.
Its like it supports the quality packages with automated testing.

2017-03-09 18:18 UTC, ankit01ojha commented
@bowlofeggs Is this fine now?

2017-03-09 19:08 UTC, bowlofeggs approved these changes
I plan to fix a few things in here, but I'll just do it in a follow up commit so we can get this merged. Thanks!

2017-03-09 19:08 UTC, merged