an idea for a new frontpage layout
fedora-infra/bodhi pull request #1405
Opened 2017-04-03 06:41 UTC by ryanlerch

Was playing around with a new idea for the frontpage layout, and came up with this approach.

Basically, the idea here is to list all the current releases, and the number of pending, testing, and stable updates for each. Additionally, each one has a count and link to the updates that fit that criteria.

Open for ideas and discussion on this one, but just thought i would get the ball rolling with a working mockup.

![fedora updates system](https://cloud.githubusercontent.com/assets/592259/24597972/60f8d692-188c-11e7-9e60-01f3c2453137.png)

2017-04-04 20:59 UTC, bowlofeggs commented
I like the design. I had an idea to also show updates that have no comments (aside from bodhi comments), to help people find updates that haven't got any feedback. Of course, that idea could be done in a separate PR, just an idea.

Anyways, I'm +1 to this change, but I would want to refine the code a bit. Since it's labeled as an idea, I'll save code comments for when you think it's ready to merge.

2017-04-05 02:28 UTC, ryanlerch commented
@bowlofeggs If you are happy with the general design, I am happy to move on to code comments!

2017-04-05 21:16 UTC, bowlofeggs requested changes
I really like this change, very nice. In addition to the changes I'm mentioning below, we will also need unit test coverage for the new Python code. If you don't want to do that, I'm happy to take that on myself. Just let me know.

2017-04-05 21:16 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +    return dict(pending_updates_total=pending_updates_total,
There are too many spaces here for [PEP-8](https://www.python.org/dev/peps/pep-0008/) and it is causing a flake8 error in the test suite:

```
/home/vagrant/bodhi/bodhi/server/views/generic.py:119:5: E303 too many blank lines (4)
F.
======================================================================
FAIL: Enforce PEP-8 compliance on the codebase.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/bodhi/bodhi/tests/test_style.py", line 37, in test_code_with_flake8
    self.assertEqual(subprocess.call(flake8_command), 0)
AssertionError: 1 != 0
```

There should just be one blank line to make flake8 happy.

2017-04-05 21:16 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +def get_update_counts(request, releaseid):
Let's give this function a docbloc. Something like this:

```
"""
Returns counts for the various states and types of updates in the given release.

This function returns a dictionary that tabulates the counts of the various types of Bodhi updates at the various states they can appear in. The dictionary has the following keys, with pretty self-explanatory names:

    pending_updates_total
    pending_newpackage_total
    pending_bugfix_total
    pending_enhancement_total
    pending_security_total
    testing_updates_total
    testing_newpackage_total
    testing_bugfix_total
    testing_enhancement_total
    testing_security_total
    stable_updates_total
    stable_newpackage_total
    stable_bugfix_total
    stable_enhancement_total
    stable_security_total

Args:
    request (pyramid.util.Request): The current request
    releaseid (basestring): The id of the Release object you would like the counts performed on
Returns:
    dict: A dictionary expressing the counts, as described above.
```

2017-04-05 21:16 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +        .filter(models.Update.type == models.UpdateType.security).count()
This function is a bit long and a bit repetitive. We should make a helper function to do the heavy lifting and then call it three times, once for each block above. Something like this:

```
def _get_status_counts(basequery, status):
    """
    Return a dictionary with the counts of objects found in the basequery, specified by total count, newpackage count, bugfix count, enhancement count, and security count. The dictionary keys will be named with the template {status}_{type}_total. For example, if status is models.UpdateStatus.stable, a dictionary with the following keys would be returned: stable_updates_total, stable_newpackage_total, stable_bugfix_total, stable_enhancement_total, stable_security_total.

    Args:
        basequery (uh, sqlalchemy.something.something? Use type(basequery) to find out what it is…): The basequery of updates we want to count and further filter on.
        status (bodhi.server.models.UpdateStatus): The update status we want to filter by in basequery
    Return:
        dict: A dictionary describing the counts of the updates, as described above.
    """
    basequery = basequery.filter(models.Update.status == status)
    return {
        '{}_updates_total'.format(status): basequery.count()
        '{}_newpackage_total'.format(status): basequery.filter(models.Update.type == models.UpdateType.newpackage).count()
        … and so forth
    }
```

Then you could just make three calls to it, and keep all the code shorter and simpler. Of course, you'd need to aggregate the return results into one dictionary, but you can use the [```dict.update```](https://docs.python.org/2/library/stdtypes.html#dict.update) method for that to make it nice and clean.

2017-04-05 21:16 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +    query = db.query(models.Update)
You could cut these two lines down to one with this:

```
query = request.db.query(models.Update)
```

You could also move it to be below the ```release =``` line below and go with:

```
basequery = request.db.query(models.Update).filter(models.Update.release == release)
```

I'm not actually a huge advocate for crazy one-liners, but I think this is still pretty readable and it cuts down on the code a bit and I think actually simplifies it.

2017-04-20 11:22 UTC, ryanlerch commented
OKies! Implemented the suggested changes.

Just not sure how to go about writing tests for these though. Is there a way to open this branch up for editing by otheres?

2017-04-20 15:38 UTC, bowlofeggs commented
@ryanlerch I think there should be some kind of checkbox on the right hand side of the pull request that you can check that says something about allowing others to edit? It is also possible for me to cherry pick your commit and add my own commit on top that has tests and I can submit a new PR that has both together. Either way is fine with me.

2017-04-20 16:05 UTC, bowlofeggs requested changes
Cool looks good except for a few style changes that are needed to get ```flake8``` to be happy. By the way, you can also run the style test alone inside the vagrant environment if you want quick validation on your style changes:

```
[vagrant@bodhi-dev ~]$ nosetests -sx ~/bodhi/bodhi/tests/test_style.py
```

2017-04-20 16:05 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +        basequery
basequery (sqlalchemy.orm.query.Query): The basequery of updates we want to count and further filter on.

2017-04-20 16:05 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +def _get_status_counts(basequery, status):
I should have been more explicit last time - PEP-8 requires exactly two blank lines between top level objects (like functions or classes), so now the test is upset that there is only one line here:

```
/home/vagrant/bodhi/bodhi/server/views/generic.py:70:1: E302 expected 2 blank lines, found 1
```

You can run the tests in vagrant by typing ```btest``` - you should see it say "OK" at the end and not "FAILED". When it fails it'll tell you what happened if you scroll above the coverage report.

2017-04-20 16:05 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +        status (bodhi.server.models.UpdateStatus): The update status we want to filter by in basequery
The automated PEP-8 tool also enforces that lines can't be over 100 characters, and this line is 102 characters:

```
/home/vagrant/bodhi/bodhi/server/views/generic.py:86:101: E501 line too long (102 > 100 characters)
```

2017-04-20 16:05 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +        '{}_security_total'.format(status.description): basequery.filter(models.Update.type == models.UpdateType.security).count(),
The PEP-8 test is also upset about these for lines for being too long:

```
/home/vagrant/bodhi/bodhi/server/views/generic.py:93:101: E501 line too long (135 > 100 characters)
/home/vagrant/bodhi/bodhi/server/views/generic.py:94:101: E501 line too long (127 > 100 characters)
/home/vagrant/bodhi/bodhi/server/views/generic.py:95:101: E501 line too long (137 > 100 characters)
/home/vagrant/bodhi/bodhi/server/views/generic.py:96:101: E501 line too long (131 > 100 characters)
```

2017-04-21 04:55 UTC, ryanlerch commented
@bowlofeggs sorry about that! 

have updated the commit with the suggested changes

thanks for the command to just run the style tests. I also just filed #1460 that adds this as an alias in the vagrant setup.

2017-05-01 14:00 UTC, bowlofeggs commented
Cool this looks good now. Let's hold off on merging it until I can write tests for it. I'll try to do that "soon", but right now I have to focus on getting 2.6.1 released so it might be a bit before I can do it. I'll just make a new commit on top of yours with tests and then I'll make a new PR with both commits.

2017-05-18 12:35 UTC, ryanlerch commented
Okies, had a go at updating the tests for this one.

Any comments on my python code are welcome!

2017-05-18 18:56 UTC, bowlofeggs requested changes

2017-05-18 18:56 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +        self.db.add(user2)
I don't think you need a user for this test since the home page should work unauthenticated, so you can probably drop these three lines.

2017-05-18 18:56 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +    def test_home_counts(self):
It would be good to add a docblock saying that this test is making sure that the home page update count report works.

2017-05-18 18:56 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +                        title=u'bodhi-2.0-1%s.fc17' % (str(count)),
I should see if I can make this many bodhi releases in 1 s too!

2017-05-18 18:56 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +                        date_submitted=datetime(1984, 11, 02),
Man, these Bodhi updates predate the Free Software movement!

2017-05-18 18:56 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +        self.assertIn('<span class="fa fa-bug"></span> 5', res)
Shouldn't this one be 4?

2017-05-18 21:01 UTC, ryanlerch commented on bodhi/tests/server/functional/test_generic.py
> +        self.assertIn('<span class="fa fa-bug"></span> 5', res)
there is already an update in there from the other tests

2017-05-19 09:10 UTC, ryanlerch commented on bodhi/tests/server/functional/test_generic.py
> +        self.db.add(user2)
Oh, from what i can gather, all tests are run authenticated (with the user "guest").

This is just creating a new user in the system to add the new updates to. The page is still logged in as guest.

2017-05-19 09:14 UTC, ryanlerch commented on bodhi/tests/server/functional/test_generic.py
> +    def test_home_counts(self):
added! thanks!

2017-05-19 09:16 UTC, ryanlerch commented on bodhi/tests/server/functional/test_generic.py
> +        self.assertIn('<span class="fa fa-bug"></span> 5', res)
Added a comment here to say that this is one extra than what we expect, because the base test code already adds an update to the system

2017-05-24 19:51 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +        self.assertIn('<span class="fa fa-bug"></span> 5', res)
Cool, thanks!

2017-05-24 20:01 UTC, bowlofeggs approved these changes
LGTM - you will need to rebase to merge due to a conflict, but feel free to merge when you've got that done. Nice work!

2017-05-25 10:41 UTC, ryanlerch commented
Rebased, and merging now.

2017-05-25 10:42 UTC, merged