Remove noisy docblocks that end up in --help text.
fedora-infra/bodhi pull request #1466
Opened 2017-04-23 13:17 UTC by nbianca

Fixes #1457.

Signed-off-by: Bianca Nenciu <nenciu.bianca@gmail.com>

2017-04-26 07:12 UTC, pypingou commented
Not entirely sure @bowlofeggs will agree with this :)

2017-05-01 14:54 UTC, bowlofeggs requested changes
Let's make sure the human readable descriptions remain, and just drop the Args blocks.

2017-05-01 14:54 UTC, bowlofeggs commented on bodhi/client/__init__.py
> -    Create a new update.
We do want to keep the descriptions - it's just the Args we don't want. The descriptions are useful in the help text.

2017-05-01 14:55 UTC, bowlofeggs commented
@pypingou I actually requested a change like this in #1457 because the Args aren't "user consumable" and actually kind of render badly too. I didn't realize that click would render those when they were written. Normally I insist on documenting parameters so that developers have good docs, but in the rare case where developer docs are at odds with good user docs, I'd rather give the users good docs ☺

2017-06-06 14:43 UTC, bowlofeggs commented
Do you still wish to work on this pull request?

2017-06-13 14:16 UTC, bowlofeggs commented
Closing due to inactivity.

2017-06-13 14:16 UTC, closed without merging