Don't show the edit update form if a user can't edit
fedora-infra/bodhi pull request #1522
Opened 2017-05-16 03:50 UTC by ryanlerch

Previously, both users that were not logged in, and
users logged in, but not having permissions to edit
an update could view the edit update form. These
users were correctly unable to submit the form, and
buttons that linked them to the form were not shown,
but if the URL was typed in, the user could still
access the form page.

This commit changes it so users that don't have
edit privs on an update get a 403 rather than the
edit form.

Fixes #1521

2017-05-17 16:20 UTC, bowlofeggs requested changes

2017-05-17 16:20 UTC, bowlofeggs commented on bodhi/server/services/updates.py
> +from pyramid.exceptions import HTTPForbidden
For [PEP-8](https://www.python.org/dev/peps/pep-0008/#imports), this import should be grouped with the other third party imports (like ```sqlalchemy```).

2017-05-17 16:20 UTC, bowlofeggs commented on bodhi/server/services/updates.py
> +        raise HTTPForbidden()
I think we could probably accomplish this by using the Pyramid ACL system. There is some code in the definition of ```update_edit``` near the top of this file that I would think should do this, but I suppose something is wrong there:

```
 53 update_edit = Service(
 54     name='update_edit', path='/updates/{id}/edit', validators=(validate_update_id,),
 55     description='Update submission service', acl=bodhi.server.security.packagers_allowed_acl,
 56     cors_origins=bodhi.server.security.cors_origins_rw)
```

I'd expect that ```acl=``` line to do the trick, but I'm not sure why it's not working. I think we should focus on fixing it that way so we're doing it "the Pyramid way".

2017-05-18 12:39 UTC, ryanlerch commented on bodhi/server/services/updates.py
> +        raise HTTPForbidden()
okies, will look into this. Although i copied this from similar code up a bit higher in the same file:

https://github.com/ryanlerch/bodhi/blob/46271695395fbd1028a523f5244b0928f5bd5e7e/bodhi/server/services/updates.py#L88

So i guess we need to change it there too.

2017-05-18 15:28 UTC, bowlofeggs commented on bodhi/server/services/updates.py
> +        raise HTTPForbidden()
@ryanlerch I *think* that one is actually using that to determine if the user should be presented with the edit buttons, for which the Pyramid ACL system wouldn't help I don't think. I'm not 100% sure, but if that is true I think that usage is probably OK.

2017-05-30 01:31 UTC, ryanlerch commented
Had a bit more of a dig around, and the ACL system goes a little over my head. For the "new update" page, we also aren't using the ACL system, but it is a little different, as we dont care there if a user can edit or not.

https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/views/generic.py#L171-L182

2017-05-30 09:34 UTC, ryanlerch commented
Updated the PR.

Ok, so i think i figured out why the `acl=` line in the `Service()` call was not working. AFAICT, we need to add a permission='something' in the @update_edit.get() decorator.

AFAICT, we don't actually specify specific permissions in bodhi/security.py. We just allow all permissions. so as long as we set something here (i went with 'edit'), the non-logged in user is not granted access to the form. We do this in other places where acls are set in the `Service()` call at the top of the file, rather than down in the decorator for the method.

Setting the permission parameter to something fixes the case for the non-logged in user, However, for the case of a logged-in user (with packager privs), but not commit access to the update, adding the  validate_acls validator checks for this. The results pass the tests, and i did a quick sanity check on a package that i own, and it seems to work, but would appriecate some other testing on this too.

2017-05-30 18:09 UTC, bowlofeggs commented
By my reading of [the Cornice docs](http://cornice.readthedocs.io/en/latest/api.html#cornice.service.Service), the acl attribute should be a function that returns a ```bool```, but it is set to [```bodhi.server.security.packagers_allowed_acl```](https://github.com/fedora-infra/bodhi/blob/2.6.2/bodhi/server/security.py#L37-L42), which returns a ```list``` instead. I suspect that may be the true issue.

The approach you have taken here does seem to be in line with the approach taken elsewhere in Bodhi, and is also [documented](http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/api/config.html#pyramid.config.Configurator.add_view) as being a reasonable approach, so I think it's fine.

As for testing, I think it would be good to write some tests in ```bodhi.tests.server.services.test_updates``` to demonstrate that the logged in user can see the view and that the non-logged-in user cannot see it.

2017-05-30 18:10 UTC, bowlofeggs commented
My hand testing also concludes that this approach works.

2017-05-31 01:42 UTC, ryanlerch commented
Updated the PR to include tests for the 3 cases of:

* Unlogged in User
* Logged in User without permissions on the update
* Logged in User with permissions on the update

2017-06-01 16:59 UTC, bowlofeggs approved these changes
Thanks!

2017-06-01 16:59 UTC, merged