PEP-257 bodhi.server.consumers.__init__.
fedora-infra/bodhi pull request #1545
Opened 2017-05-24 19:16 UTC by bowlofeggs

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

2017-05-24 19:46 UTC, ralphbean commented on bodhi/tests/test_style.py
> +            'bodhi/server/consumers/__init__.py', 'bodhi/server/scripts/__init__.py',
Nonblocking comment here:

I recommend breaking these out into one item per line.

It makes it much easier to review -- to see what was added and what was changed.

2017-05-24 19:46 UTC, ralphbean approved these changes
LGTM.

2017-05-25 13:04 UTC, ralphbean requested changes
Eh, merge conflict now.  @bowlofeggs can you rebase?

2017-05-25 14:38 UTC, ralphbean approved these changes
Good to go.

2017-05-25 14:38 UTC, merged

2017-05-25 14:39 UTC, bowlofeggs commented on bodhi/tests/test_style.py
> +            'bodhi/server/consumers/__init__.py', 'bodhi/server/scripts/__init__.py',
Fixed!