Pending update directly requests for stable if it hits stable karma
fedora-infra/bodhi pull request #1556
Opened 2017-05-27 09:21 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>
Fixes #632

2017-05-31 14:17 UTC, bowlofeggs commented on bodhi/server/models.py
>          # Return if the status of the update is not in testing
This comment should be updated.

2017-05-31 14:17 UTC, bowlofeggs commented on bodhi/server/models.py
> +        if self.autokarma and self._composite_karma[1] != 0 and self.status is UpdateStatus.testing:
Why would we only want to disable autokarma for testing updates? It seems to me that we should treat the pending updates the same way.

2017-05-31 14:17 UTC, bowlofeggs commented on bodhi/server/models.py
> +                and self.status is UpdateStatus.testing:
Similarly here - why treat the testing update differently than the pending one?

2017-05-31 14:17 UTC, bowlofeggs commented on bodhi/tests/server/services/test_updates.py
> +        self.assertNotIn('Push to Stable', resp)
Wouldn't we want ```self.assertIn('Push to Stable', resp)``` here instead?

2017-06-13 15:53 UTC, bowlofeggs requested changes
There seem to be 5 failing tests. Here's one of them:

```
======================================================================
FAIL: test_commenting_twice_with_positive_then_negative_karma (bodhi.tests.server.functional.test_comments.TestCommentsService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/vagrant/bodhi/bodhi/tests/server/functional/test_comments.py", line 193, in test_commenting_twice_with_positive_then_negative_karma
    self.assertEquals(res.json_body['comment']['text'], 'Test')
AssertionError: u'Bodhi is disabling automatic push to stable due to negative karma. The maintainer may push manually if they determine that the issue is not severe.' != 'Test'
```

2017-06-13 15:53 UTC, bowlofeggs commented
ok test

2017-06-26 12:32 UTC, trishnaguha commented on bodhi/server/models.py
> +        if self.autokarma and self._composite_karma[1] != 0 and self.status is UpdateStatus.testing:
@bowlofeggs We would want to disable autokarma **only** for testing updates as this is conflicting with https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L2380 for pending updates.
As we would not like to disable autopush for pending updates on unstable karma, rather we want to send it to `obsolete` state https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/services/test_updates.py#L2397

2017-06-26 12:34 UTC, trishnaguha commented on bodhi/server/models.py
> +                pass
For pending updates with unstable karma (but with disabled autopush), we would not like to send it to `obsolete` state automatically https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/services/test_updates.py#L2423

2017-06-26 15:57 UTC, bowlofeggs commented
test

2017-06-26 16:07 UTC, bowlofeggs approved these changes

2017-06-26 16:09 UTC, merged

2017-06-26 16:17 UTC, bowlofeggs commented
I opened https://github.com/fedora-infra/bodhi/pull/1651 to add one more assertion to one of these tests.