Use specific package subclass in query.
fedora-infra/bodhi pull request #1562
Opened 2017-05-30 13:47 UTC by ralphbean

This fixes a MultipleResultsFound error I got from sqlalchemy when trying to
create my demo of #1543:  https://fedorapeople.org/groups/factory2/sprint-031/threebean-modular-bodhi-updates.ogv

The "package" in question here was "nginx"... but do I want the nginx
RpmPackage or the nginx ModulePackage?  Specificity required!

2017-05-31 07:13 UTC, mcurlej commented
LGFM

2017-05-31 20:03 UTC, bowlofeggs requested changes
It would be good to write a test for this change. Perhaps a test that submits a new update here, and we can mock the Koji data to make it be a module and assert that the right Package subclass was used?

2017-06-30 13:57 UTC, bowlofeggs commented
@ralphbean Do you still want to work on this?

2017-07-20 01:07 UTC, ryanlerch commented
jenkies test

2017-07-20 03:09 UTC, ralphbean commented
I forgot all about this change!  I'll try to revisit it in the next few days.

2017-07-21 20:31 UTC, ralphbean commented
Rebased on `develop`.

> It would be good to write a test for this change.

Added test in 6b51ce1.

2017-07-24 16:09 UTC, bowlofeggs approved these changes
Thanks!

2017-07-24 16:09 UTC, merged