Improve test coverage for util.py
fedora-infra/bodhi pull request #1568
Opened 2017-05-31 14:14 UTC by ryanlerch

* Adds tests for getting RPM headers from koji
* Adds tests for the splitter() method in util.py
* Remove unused Singleton class
* Remove unused get_repo_tag() method

2017-05-31 21:02 UTC, bowlofeggs requested changes
```deleting_unused_code++```

2017-05-31 21:02 UTC, bowlofeggs commented on bodhi/tests/server/test_utils.py
> +        print splitspacestring
Let's drop the two print statements.

2017-05-31 21:02 UTC, bowlofeggs commented on bodhi/tests/server/test_utils.py
> +        assert splitlist[1] == "build-0.2"
For all three of these test blocks, you could replace the assertions with a one liner that also asserts that the length is 2:

```
self.assertEqual(splitlist, ['build-0.1', 'build-0.2'])
```

2017-06-01 05:23 UTC, ryanlerch commented on bodhi/tests/server/test_utils.py
> +        assert splitlist[1] == "build-0.2"
Done. I had to make the class in this file extend unittest.TestCase to be able to use assertEqual though.

2017-06-01 05:24 UTC, ryanlerch commented on bodhi/tests/server/test_utils.py
> +        print splitspacestring
Done! Sorry about leaving debugging stuff in there :/

2017-06-01 15:22 UTC, bowlofeggs commented on bodhi/tests/server/test_utils.py
> +        assert splitlist[1] == "build-0.2"
Oh right, I'd forgotten about that. Some day I hope to unify the tests a bit more so they at least all subclass ```unittest.TestCase```.

2017-06-01 15:27 UTC, bowlofeggs approved these changes
Awesome, thanks!

2017-06-01 15:28 UTC, merged