Provide messenging if user tries to create a new override that already exists
fedora-infra/bodhi pull request #1608
Opened 2017-06-15 03:03 UTC by ryanlerch

This commit provides better error messages to the user if they try
to create an override with bodhi-client that already exists.

fixes #1377

2017-06-17 02:46 UTC, bowlofeggs requested changes
The new lines are missing coverage:

```
Failure. Coverage is below 100.0%.
-------------
Diff Coverage
Diff: develop...HEAD, staged, and unstaged changes
-------------
bodhi/client/__init__.py (28.6%): Missing lines 462-466
-------------
Total:   7 lines
Missing: 5 lines
Coverage: 28%
-------------
```

2017-06-17 02:46 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +            click.echo("Use `overrides edit` to edit an existing override")
I would suggest moving the ```click.echo()``` into the ```if``` block, and adding an ```else``` with ```raise```, so other errors still print a traceback. That way we can get better debugging info if users experience a different problem than this one.

2017-06-19 02:55 UTC, ryanlerch commented on bodhi/client/__init__.py
> +            click.echo("Use `overrides edit` to edit an existing override")
Did this, thanks!

2017-06-19 02:57 UTC, ryanlerch commented
Added the additional tests as well.

bdiffcover is pretty neat!

2017-06-19 23:12 UTC, bowlofeggs approved these changes
Both comments are just suggestions at your option. No need for re-review if you decide to go with them, so merge as you please!

2017-06-19 23:12 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +            click.echo("Use `overrides edit` to edit an existing override")
I recommend adding a period on the end of each of these sentences.

2017-06-19 23:12 UTC, bowlofeggs commented on bodhi/tests/client/test___init__.py
> +            ['--user', 'bowlofeggs', '--password', 's3kr3t', 'js-tag-it-2.0-1.fc25'])
Just a recommendation (feel free to ignore): I suggest adding a space here. I like to group my tests into three groups visually, using spaces to separate them. The first group is code that sets up the test (like you have above this line). The middle group is usually a 1-liner that runs the thing being tested (i.e., this line). And the last group is the assertions that the right thing happened. It's just a personal preference, and just a suggestion ☺

2017-06-19 23:12 UTC, bowlofeggs commented on bodhi/tests/client/test___init__.py
> +        send_request.side_effect = bindings.BodhiClientException("Pants Exception")
haha

2017-06-20 04:14 UTC, ryanlerch commented on bodhi/client/__init__.py
> +            click.echo("Use `overrides edit` to edit an existing override")
Added the fullstops. Thanks! ;)

2017-06-20 04:14 UTC, ryanlerch commented on bodhi/tests/client/test___init__.py
> +            ['--user', 'bowlofeggs', '--password', 's3kr3t', 'js-tag-it-2.0-1.fc25'])
I like this, it makes sense to me! Added!

2017-06-20 04:18 UTC, merged