add pending releases to the frontpage
fedora-infra/bodhi pull request #1623
Opened 2017-06-19 14:36 UTC by ryanlerch

Previously, the new frontpage only included 'current' releases. This commit adds pending releases also, with pending releases having a label 'prerelease' in next to the release name.

Fixes: #1619

2017-06-20 10:36 UTC, pypingou commented
Change in itself looks fine, screenshot ? :)

2017-06-22 20:52 UTC, bowlofeggs commented
test

2017-06-23 15:08 UTC, bowlofeggs requested changes
Don't worry about the CI - CI won't work until #1631 is merged.

2017-06-23 15:08 UTC, bowlofeggs commented on bodhi/server/views/generic.py
> +        for release in request.releases['current'] + request.releases['pending']:
We should test that these pending releases get included here.

2017-06-27 05:27 UTC, ryanlerch commented
Added the test.

However, there is an issue. For some reason, when i run the tests by themselves, i.e:
```
btest --tests bodhi/tests/server/functional/test_generic.py
```

They pass fine. But the same test fails when trying to run the whole test suite (i.e. `btest`). I tried to figure out what was going on here, but it really stumped me. There is something about adding the extra release in the test that is not being picked up.

2017-06-27 15:54 UTC, bowlofeggs commented
test

2017-06-27 16:25 UTC, bowlofeggs commented on bodhi/server/views/generic.py
>          critpath_updates = get_latest_updates(request, True, False)
This function is cached - that might be the cause of the test isolation problems.

2017-06-27 16:42 UTC, bowlofeggs commented on bodhi/server/views/generic.py
>          critpath_updates = get_latest_updates(request, True, False)
I tried disabling the cache and it didn't help, so I was wrong.

2017-06-27 16:57 UTC, jeremycline commented
In my database test refactoring work, I've also found bodhi/tests/server/functional/test_generic.py to be very fragile and order-dependent. I plan to track the problem down as part of that refactoring work and fix it. I'm not sure how long it will take though, I spent a good bit of yesterday investigating a different set of order-dependent tests :(.

Maybe by the end of the week?

2017-06-27 17:00 UTC, bowlofeggs commented
@ryanlerch Why don't we wait and see what @jeremycline comes up with - perhaps you will be able to simply rebase on a commit from him and everything will be fine?

2017-06-27 20:35 UTC, ryanlerch commented
@jeremycline @bowlofeggs thanks for looking into this!

2017-07-03 02:07 UTC, ryanlerch commented
Just rebased this PR to include the recent changes to the test infrastruture that @jeremycline implemented in #1664 , and the test now works when running all the tests. Thanks @jeremycline & @bowlofeggs !

2017-07-03 19:08 UTC, bowlofeggs requested changes
The releases visually cascade with this change:

![delme](https://user-images.githubusercontent.com/354506/27805208-5f3fb412-6001-11e7-8e5a-c5ca74b97efc.png)

The code looks good though - can we get the releases to line up?

2017-07-04 00:54 UTC, ryanlerch commented
@bowlofeggs thanks for catching the lining up issue, mucked up the rebase there, sorry!

Updated the commit to fix an extra div that was causing the cascading issue, and this one should be right to go!

cheers,
ryanlerch

2017-07-05 19:28 UTC, bowlofeggs requested changes
Just one tiny fix left, looks good!

2017-07-05 19:28 UTC, bowlofeggs commented on bodhi/tests/server/functional/test_generic.py
> +        print res
Let's drop this print statement.

2017-07-05 20:26 UTC, bowlofeggs commented
Feel free to merge once that print statement is dropped!

2017-07-06 10:20 UTC, ryanlerch commented
Hi Jenkies!

It was failing because i hadn't changed the base test class to the new one that @jeremycline pushed recently. Just updated the PR to use the new testing base class.

2017-07-06 10:34 UTC, ryanlerch commented
Thanks for testing it again Jenkies. :D 

@bowlofeggs i also removed the print statement (thanks for catching that one!)

merging now!

2017-07-06 10:34 UTC, merged