Add '--requirements' flag to CLI
fedora-infra/bodhi pull request #1638
Opened 2017-06-21 17:45 UTC by crungehottman

Permits users to set required Taskatron tasks in the CLI via a '--requirements' flag.

fixes #1319

2017-06-21 19:30 UTC, cverna commented
Looks good, it would be good to add the new option to the man page too. See https://github.com/fedora-infra/bodhi/blob/develop/docs/man_pages/bodhi.rst

👍

2017-06-22 21:01 UTC, bowlofeggs requested changes

2017-06-22 21:01 UTC, bowlofeggs commented on docs/man_pages/bodhi.rst
> +    ``--requirements <Taskatron tasks>``
It's spelled Taskotron (though the [cool looking] logo font makes it a little ambiguous): https://taskotron.fedoraproject.org/

2017-06-22 21:01 UTC, bowlofeggs commented on docs/man_pages/bodhi.rst
> +        A comma or space-separated list of required Taskatron tasks that must pass for this update
Taskotron here too

2017-06-22 21:01 UTC, bowlofeggs commented on docs/man_pages/bodhi.rst
> +        to reach stable.
@kparal is the intention for these tests to stop broken updates from reaching stable, or updates-testing?

2017-06-22 21:01 UTC, bowlofeggs commented on docs/man_pages/bodhi.rst
> +        A comma or space-separated list of required Taskatron tasks that must pass for this update
Taskotron here and the line above too.

2017-06-22 21:01 UTC, bowlofeggs commented
test

2017-06-23 08:03 UTC, kparal commented on docs/man_pages/bodhi.rst
> +        to reach stable.
@bowlofeggs All tests are targeting stable so far, but in theory we could add tests that target updates-testing in the future. That would likely require more changes, though, and is not probably anything short-term.

2017-06-23 17:20 UTC, bowlofeggs commented on docs/man_pages/bodhi.rst
> +        to reach stable.
Cool, then it sounds like this docblock is correct.

2017-06-26 14:56 UTC, bowlofeggs commented
test

2017-06-26 15:12 UTC, bowlofeggs approved these changes
Thanks!

2017-06-26 15:13 UTC, merged