Add python-click's bash completion activation script
fedora-infra/bodhi pull request #1639
Opened 2017-06-21 18:59 UTC by crungehottman

This commit will allow users to enable bash completion via shipping an activation script. 

To activate the activation script, the user would simply need to place the following line somewhere in his/her/their vagrant .bashrc:
`. ~/bodhi/bodhi-complete.sh`

If the user does not add the previous line to his/her/their .bashrc, no errors will occur, bash completion will simply not be enabled.

For a flawless UI experience, it should be recommended that the user also ignore python warnings by changing the following line in the .bashrc

`export PYTHONWARNINGS="once"
`

to

`export PYTHONWARNINGS="ignore"
`

Example:
![image](https://user-images.githubusercontent.com/13953722/27401170-be2910a8-567f-11e7-8744-28931ee3ac74.png)

_Please note that this PR does not intend to provide total and dynamic bash completion, as python-click has yet to implement the ability of dynamic completion._

Examples of Bodhi using python-click's available bash completion:

![image](https://user-images.githubusercontent.com/13953722/27401185-c90128f8-567f-11e7-8d65-23578aef0643.png)

![image](https://user-images.githubusercontent.com/13953722/27401191-cb799c00-567f-11e7-8bb7-b6bffbfb3418.png)

source: http://click.pocoo.org/5/bashcomplete/

2017-06-22 01:42 UTC, ryanlerch commented
#1188

2017-06-22 21:02 UTC, bowlofeggs commented
@crungehottman Can you amend your commit message to have it's own line with ```fixes #1188```?

2017-06-22 21:08 UTC, bowlofeggs requested changes
The script looks good (I guess that's just what click autogenerates.) How about we modify the dev role to drop a symlink to this file in ```/etc/bash_completion.d/``` on the Vagrant box? You could add that in [this file](https://github.com/fedora-infra/bodhi/blob/2.8.1/devel/ansible/roles/dev/tasks/main.yml).

I personally think the warnings are good in the dev environment, even though they kinda mess up the bash completion. There may be a way to set PYTHONWARNINGS to the default in the dev environment when bash completion is being used. I don't immediately have an idea for that and it's not a requirement to merge this patch, just a thought.

Once this is in a release, I can modify the downstream spec files to drop this file into the rpms so they work in Fedora and EPEL!

2017-06-23 19:22 UTC, crungehottman commented
I agree re: thinking warnings are good in the dev environment. In my limited experience with bodhi, I have only encountered python warnings while using btest and bash completion. Besides during btest, when else might someone want python warnings?

I ask because I found a simple way to enable warnings in btest and disable them otherwise:
![image](https://user-images.githubusercontent.com/13953722/27497055-fbdab978-5815-11e7-8e7d-0deba6b8a033.png)
![image](https://user-images.githubusercontent.com/13953722/27497057-ff77ed8a-5815-11e7-99c9-2f47c5f128d2.png)

2017-06-24 22:13 UTC, bowlofeggs commented
On Fri, 2017-06-23 at 12:22 -0700, Caleigh Runge-Hottman wrote:
> I agree re: thinking warnings are good in the dev environment. In my
> limited experience with bodhi, I have only encountered python
> warnings while using btest and bash completion. Besides during btest,
> when else might someone want python warnings?

That's a good point - so we could consider only setting PYTHONWARNINGS
on certain commands. I'd say it's probably useful in the server logs
(which is run in systemd, and I *think* I might have also set it there?
Can't remember, but it'd be easy to do if I didn't…), btest as you
said, and probably fedmsg-hub. So yeah, if you want to make it so I say
go 4 it.

2017-06-26 15:21 UTC, bowlofeggs approved these changes
Thanks!

2017-06-26 15:21 UTC, merged