PEP-257 bodhi.server.services.overrides.
fedora-infra/bodhi pull request #1760
Opened 2017-08-17 13:27 UTC by bowlofeggs

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

2017-08-31 15:39 UTC, jeremycline requested changes
There's one docblock that looks slightly incorrect (dict rather than some JSON-serialized string). Other than that, this looks good.

:shipit:

2017-08-31 15:39 UTC, jeremycline commented on bodhi/server/services/overrides.py
> +        basestring: A JSON response describing the new or edited override.
It looks to me like this is returning a dictionary

2017-09-06 16:24 UTC, bowlofeggs commented
@jeremycline I've corrected the docblock and rebased to resolve a merge conflict. How does it look now?

2017-09-15 14:34 UTC, jeremycline approved these changes
Go forth and :shipit: with my blessing

2017-09-15 15:12 UTC, merged