Add indexes for status and request
fedora-infra/bodhi pull request #1944
Opened 2017-10-26 20:57 UTC by tyll

2017-10-27 09:49 UTC, ryanlerch commented
jenkies test

2017-10-30 23:42 UTC, ryanlerch commented
@centos-ci test this please

2017-10-31 17:45 UTC, bowlofeggs requested changes
This looks good! We just have a few style checkers that are upset (you can see these buried in the Jenkins output), but I've commented on all the things the checkers were upset about below. The migration looks good and seems to work.

2017-10-31 17:45 UTC, bowlofeggs commented on bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
> +Add indexes for status and request
pydocstyle wants a period on the end of this sentence.

2017-10-31 17:45 UTC, bowlofeggs commented on bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
> +    ### commands auto generated by Alembic - please adjust! ###
pydocstyle wants a docblock here. How about this:

```
"""
Add indices to the request and status columns on the update table, and add a compound uniqueness constraint on the Package's name and type.
"""
```

Similarly, pydocstyle wants a docblock on the ```downgrade()``` function below and we can probably just reverse the above sentence to say its removing those indices/constraints.

2017-10-31 17:45 UTC, bowlofeggs commented on bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
> +    ### end Alembic commands ###
I suggest removing the autogenerated Alembic comments from this file.

2017-10-31 17:45 UTC, bowlofeggs commented on bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
> +import sqlalchemy as sa
This import isn't used so we should drop it.

2017-10-31 17:45 UTC, bowlofeggs commented on bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
> +
Let's remove one of these three blank lines so there are two, for PEP-8.

2017-11-21 20:07 UTC, bowlofeggs commented on bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
> +    op.create_unique_constraint('packages_name_and_type_key', 'packages', ['name', 'type'])
I added this in https://github.com/fedora-infra/bodhi/pull/2039, so we don't need it here or in ```downgrade()``` below.

2018-01-10 16:59 UTC, bowlofeggs commented
Hello @tyll, do you still want to work on this?

2018-01-11 22:44 UTC, tyll commented
On Wed, Jan 10, 2018 at 04:59:45PM +0000, Randy Barlow wrote:
> Hello @tyll, do you still want to work on this?

Thank you for your patience and the feedback. I updated the commit.

2018-01-12 21:57 UTC, bowlofeggs commented
jenkies test

2018-01-16 14:38 UTC, bowlofeggs commented
Hi @tyll!

I am going to force push your branch to fix up a couple things to get this ready to merge. Thanks for the patch!

2018-01-16 15:11 UTC, bowlofeggs commented
jenkies test

2018-01-16 17:18 UTC, bowlofeggs approved these changes
Thanks!

2018-01-16 17:18 UTC, merged

2018-02-09 19:21 UTC, bowlofeggs commented
The patch for this feature has been included in the [```3.3.0b0``` build](https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html), which is currently deployed to [staging](https://bodhi.stg.fedoraproject.org).