Use plain ASCII for alembic template
fedora-infra/bodhi pull request #1948
Opened 2017-10-27 17:07 UTC by tyll

For unknown reasons alembic strips the first line of the template when
creating a migration script. Then the utf-8 characters leads to an
encoding error.

2017-10-27 17:08 UTC, puiterwijk commented
@centos-ci please test

2017-10-27 17:10 UTC, puiterwijk commented
@centos-ci test this please

2017-10-31 17:47 UTC, bowlofeggs requested changes
Thanks!

2017-10-31 17:47 UTC, bowlofeggs commented on bodhi/server/migrations/script.py.mako
>  # -*- coding: utf-8 -*-
Let's drop this line too, since it was only here to accomodate the © character.

2017-11-21 17:45 UTC, bowlofeggs commented
I just hit this bug so I'm going to merge this. I'll make a new PR with my requested change to drop that encoding header.

2017-11-21 17:45 UTC, merged

2017-11-21 17:48 UTC, bowlofeggs commented on bodhi/server/migrations/script.py.mako
>  # -*- coding: utf-8 -*-
I opened #2037 with this suggested change.