Store a single completed repo
fedora-infra/bodhi pull request #1987
Opened 2017-11-11 13:39 UTC by puiterwijk

This also fixes resuming with completed repository, since we no longer care about the entire repo path, so "self.id" is very likely not to be in there.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2017-11-13 21:12 UTC, bowlofeggs requested changes

2017-11-13 21:12 UTC, bowlofeggs commented on bodhi/tests/server/consumers/test_masher.py
> +        self.assertIsNotNone(t.state['completed_repo'])
Can we change these ```self.assertIsNotNone```'s to ```self.assertEqual```'s? That way we have stronger assertions and can make sure that they are the right value too.

2017-11-13 21:13 UTC, bowlofeggs commented
jenkies test

2017-11-13 22:28 UTC, bowlofeggs commented
This test failure appears to be real.

2017-12-06 18:51 UTC, bowlofeggs commented
I think I've incorporated this change into #2052. If you agree, shall we close this PR?

2018-01-10 17:06 UTC, puiterwijk commented
@bowlofeggs++

2018-01-10 17:06 UTC, closed without merging