Include update severity level in updateinfo.xml
fedora-infra/bodhi pull request #2099
Opened 2017-12-21 20:25 UTC by jlebon

Right now, doing a `dnf list-sec` shows e.g.:

```
FEDORA-2017-fb5e227432 Unknown/Sec. glibc-2.26-20.fc27.x86_64
```

The `Unknown` in the output is due to the fact that `updateinfo.xml`
doesn't seem to include the severity level of the security update even
though the update does have it set (to "low" in this case). RHEL
repodata on the other hand does include this, and it shows up in `yum
list-sec`.

This is an important factor for users when determining when to apply the
updates. So let's include it in the XML.

Signed-off-by: Jonathan Lebon <jlebon@redhat.com>

2017-12-21 20:29 UTC, jlebon commented
Let me know if forgot to update (pun intended) something somewhere!

I've also verified on the client side that `dnf list-sec` picks this up and displays it correctly:

```
$ sudo dnf  --disablerepo='*' --enablerepo=bodhitest --enablerepo=bodhitest2 list-sec all
Repository 'bodhitest' is missing name in configuration, using id.
Repository 'bodhitest2' is missing name in configuration, using id.
Repository 'fahc' is missing name in configuration, using id.
bodhitest                                                                              966 kB/s | 989  B     00:00
Last metadata expiration check: 0:00:00 ago on Thu 21 Dec 2017 08:15:12 PM UTC.
  FEDORA-2017-ad1937a146 Moderate/Sec. TurboGears-1.0.2.2-2.fc17.noarch
```

We'll be making use of this in rpm-ostree as well in the context of [automatic updates](https://github.com/projectatomic/rpm-ostree/issues/247).

2018-01-08 15:57 UTC, jlebon commented
📞 Can someone have a look at this? Thanks!

2018-01-10 17:52 UTC, bowlofeggs requested changes
Just one requested change, looks good otherwise!

Also sorry for the delay in looking at this - I've been AFK for more than three weeks!

2018-01-10 17:52 UTC, bowlofeggs commented on README.rst
> +.. _developer documentation: https://bodhi.fedoraproject.org/docs/developer_docs.html
This change is unrelated, but is also actually a regression - the upcoming 3.2.0 release will make the existing link correct once it is deployed to production.

2018-01-10 17:52 UTC, bowlofeggs commented
jenkies test

2018-01-10 18:00 UTC, jlebon commented
Thanks, dropped that commit! ⬆️

2018-01-12 21:54 UTC, bowlofeggs approved these changes

2018-01-12 21:54 UTC, bowlofeggs commented
jenkies test

2018-01-15 16:46 UTC, jlebon commented
Fixed flake8 failure! ⬆️

2018-01-16 14:17 UTC, bowlofeggs commented
I just rebased your branch to fix a merge conflict. Once the CI tests pass (fingers crossed) we'll be good to merge!

2018-01-16 14:17 UTC, bowlofeggs commented
jenkies test

2018-01-16 15:58 UTC, bowlofeggs commented
Ah, simple docstyle fix - I'll take care of it for you!

2018-01-16 17:17 UTC, bowlofeggs commented
jenkies test

2018-01-16 18:52 UTC, merged

2018-02-09 19:21 UTC, bowlofeggs commented
The patch for this feature has been included in the [```3.3.0b0``` build](https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html), which is currently deployed to [staging](https://bodhi.stg.fedoraproject.org).