Change the logic of --close-bugs flag.
fedora-infra/bodhi pull request #2149
Opened 2018-02-13 12:58 UTC by cverna

This commit makes using the --close-bugs flag set
the boolean to True instead of False previously

Fixes #1818

Signed-off-by: Clement Verna <cverna@tutanota.com>

2018-02-26 18:58 UTC, bowlofeggs commented
@centos-ci add to whitelist

2018-02-26 19:01 UTC, bowlofeggs requested changes
Thanks so much for the patch! We just need a change to the release notes and this should be good to go (assuming CI also passes - it's running now).

2018-02-26 19:01 UTC, bowlofeggs commented on docs/user/release_notes.rst
> +* Clément Verna
The 3.3.0 release is already out the door and into production - can you move the two lines you changed here into a new ```develop``` heading at the top?

2018-02-26 19:41 UTC, bowlofeggs commented
jenkies test

2018-02-27 12:04 UTC, cverna commented
I have updated the release notes and rebased the PR.

2018-02-28 17:49 UTC, bowlofeggs approved these changes
Thanks!

2018-02-28 17:50 UTC, merged