Use ':' as separator for name:stream:version in pungi variants.xml wh…
fedora-infra/bodhi pull request #2167
Opened 2018-02-22 11:33 UTC by hanzz

…en mashing modules.

Signed-off-by: Jan Kaluza <jkaluza@redhat.com>

2018-02-22 11:35 UTC, puiterwijk commented
@centos-ci add to whitelist

2018-02-26 14:24 UTC, bowlofeggs requested changes
There are tests that assert that exceptions are raised by ```_raise_on_get_build_multicall_error```, but we will also need tests that assert that the correct data is returned (with :'s) from ```_generate_module_list``` when there are not koji errors.

2018-02-26 14:24 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +                version = koji_build["release"]
This code block is almost identical to the code block above. Let's replace it with a method so we can adjust them together in the future if needed.

2018-03-07 20:12 UTC, bowlofeggs reviewed
Just a nitpick on a docblock.

I'm running the tests now on my laptop.

2018-03-07 20:12 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +            newest_builds (dict): Dict with name:stream as a key and version as a value.
It looks like the value is actually a dictionary with the key "version" (perhaps among others?) based on reading the code below:

```
curr_version = newest_builds[ns]['version']
```

2018-03-07 20:24 UTC, bowlofeggs approved these changes
Alright, I've run CI for this on my laptop and it passes, so I think we are good to merge. Please correct that one docblock I mentioned earlier, but no need for re-review.

2018-03-07 21:39 UTC, merged