Don't downgrade bug status from VERIFIED or CLOSED to ON_QA
fedora-infra/bodhi pull request #2168
Opened 2018-02-22 18:52 UTC by mattiaverga

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>
Fixes #1091 #1349 

This patch checks if a bug is already in VERIFIED or CLOSED status and avoids to downgrade it to ON_QA.
Also, if the bug is already in ON_QA it just add a new comment without set again the ON_QA state (for example when an update on multiple Fedora branches is linked to a bug)

2018-02-26 14:08 UTC, bowlofeggs requested changes
The code change looks good, but let's add some tests to ensure it operates properly. There is a test module for this code at ```bodhi/tests/server/test_bugs.py```. Thanks!

2018-02-26 14:08 UTC, bowlofeggs commented
jenkies test

2018-02-26 19:23 UTC, mattiaverga commented
I've added a test case when a bug is already in 'CLOSED' status. Should I add another for the 'VERIFIED' status?

2018-02-26 20:03 UTC, bowlofeggs commented
On 02/26/2018 02:23 PM, Mattia Verga wrote:
> I've added a test case when a bug is already in 'CLOSED' status. Should
> I add another for the 'VERIFIED' status?

Yeah, I would also add one for the ```ON_QA``` status, so that you hit
all four of the branches in the if statement (there are already tests
for the fourth condition where we *do* want to change the status).

2018-02-26 20:03 UTC, bowlofeggs commented
jenkies test

2018-02-26 20:33 UTC, bowlofeggs commented
I've observed this CI failure a few times, and am not sure what causes it, but usually re-running it works.

2018-02-26 20:33 UTC, bowlofeggs commented
jenkies test

2018-02-28 18:40 UTC, bowlofeggs approved these changes
Thanks so much!

2018-02-28 18:40 UTC, bowlofeggs commented
jenkies test

2018-02-28 19:31 UTC, merged