Require comments to have text in them
fedora-infra/bodhi pull request #2172
Opened 2018-02-23 07:48 UTC by CalvinWu4

In response to https://github.com/fedora-infra/bodhi/issues/2009

2018-02-26 13:59 UTC, bowlofeggs commented
jenkies test

2018-02-26 14:01 UTC, bowlofeggs requested changes
We will want tests for this change. You can add tests at ```bodhi/tests/server/test_models.py```.

2018-02-26 14:01 UTC, bowlofeggs commented on bodhi/server/models.py
> +            raise ValueError('You must provide text in comment')
As @mattiaverga commented in #2009, we don't necessarily want to restrict users from providing only karma. I suggest changing this to ```if not text and not karma```.

2018-02-26 19:43 UTC, bowlofeggs commented
Please also amend your commit message to sign the Developer Certificate of Origin as documented in Bodhi's [contributor guidelines](https://bodhi.fedoraproject.org/docs/developer/index.html#contribution-guidelines).

2018-02-26 19:44 UTC, bowlofeggs commented on bodhi/server/models.py
> +
The CI test failure is due to this line containing whitespace:

```
f26	./bodhi/server/models.py:2751:1: W293 blank line contains whitespace
f26	            
f26	^
```

2018-03-29 17:16 UTC, bowlofeggs commented
@CalvinWu4 Do you still want to work on this?

2018-03-29 17:21 UTC, CalvinWu4 commented
I am currently busy with schoolwork at the moment but I may be able to work on this during the summer

2018-03-29 18:40 UTC, bowlofeggs commented
OK, I am going to close this pull request for now. Feel free to reopen it when you have time to work on it.

2018-03-29 18:40 UTC, closed without merging