Fix article in tooltip on update page.
fedora-infra/bodhi pull request #2242
Opened 2018-03-23 20:49 UTC by relrod

Signed-off-by: Rick Elrod <rick@elrod.me>

2018-03-26 14:08 UTC, bowlofeggs requested changes

2018-03-26 14:08 UTC, bowlofeggs commented on bodhi/server/util.py
> +            " % (cls, kind_article, kind, fontawesome)
Looks like we just need to add some test coverage to this to get CI to be happy. You can add the tests at ```bodhi.tests.server.test_util```. I think we could probably get by with two tests. Here's some untested handy-wavy pseudocode to get you started:

```
def test_consonant(self):
    """Test type2icon() with a kind that starts with a consonant."""
    self.assertEqual(util.type2icon('security'), 
                               ("<span class='label label-%s' data-toggle='tooltip'"
                                "title='This is a security update'><i class='fa fa-fw danger'></i></span> "))

def test_vowel(self):
    """Test type2icon() with a kind that starts with a vowel."""
    self.assertEqual(util.type2icon('enhancement'), 
                               ("<span class='label label-%s' data-toggle='tooltip'"
                                "title='This is an enhancement update'><i class='fa fa-fw success'></i></span> "))
```

2018-04-26 21:11 UTC, bowlofeggs commented
Hi @relrod, do you still want to work on this?

2018-07-23 19:27 UTC, bowlofeggs commented
I am going to add these two tests.

2018-07-23 20:16 UTC, bowlofeggs approved these changes

2018-07-23 20:20 UTC, relrod commented
+1

2018-07-23 20:22 UTC, bowlofeggs commented
jenkies test

2018-07-23 20:55 UTC, bowlofeggs commented
jenkies test

2018-07-23 21:32 UTC, merged

2018-08-28 17:34 UTC, bowlofeggs commented
These patches are planned to be included in the upcoming 3.10.0 release: #2556.

2018-08-31 16:38 UTC, bowlofeggs commented
These patches have been deployed to Fedora's staging Bodhi instance:

https://bodhi.stg.fedoraproject.org/