Implement fake tags and addTag/deleteTag
fedora-infra/bodhi pull request #2279
Opened 2018-04-12 14:54 UTC by puiterwijk

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2018-04-24 13:23 UTC, bowlofeggs commented
The test failure was unrelated to this patch, but required the patch to be rebased onto the latest develop with the fix. I've force pushed your branch to fix that.

2018-04-24 13:23 UTC, bowlofeggs approved these changes

2018-04-24 14:06 UTC, bowlofeggs requested changes
Just two docblock changes needed to satisfy pydocstyle.

2018-04-24 14:06 UTC, bowlofeggs commented on bodhi/server/buildsys.py
> +        """ Emulate tag adding. """
The test failure was due to the spaces around this sentence:

```
rawhide	bodhi/server/buildsys.py:446 in public method `addTag`:
rawhide	        D210: No whitespaces allowed surrounding docstring text
```

2018-04-24 14:06 UTC, bowlofeggs commented on bodhi/server/buildsys.py
> +        """ Emulate tag deletion. """
```
rawhide	bodhi/server/buildsys.py:462 in public method `deleteTag`:
rawhide	        D210: No whitespaces allowed surrounding docstring text
```

2018-04-24 18:58 UTC, bowlofeggs requested changes

2018-04-24 18:58 UTC, bowlofeggs commented on bodhi/server/buildsys.py
> +        raise NotImplementedError
Hmm, looks like CI is upset about missing coverage on the above two methods. I added a really [dumb test](https://github.com/fedora-infra/bodhi/blob/3.6.1/bodhi/tests/server/test_buildsys.py#L32-L43) to hit the other methods here, so you could just add to that.

I also think it's reallllly dumb that we have this class at all. We could also just kill the entire class if you want. I really don't see what purpose it serves - it's not like Koji subclasses it - only ```DevBuildsys``` does, and it has its own methods anyway.

Either of the above solutions are fine by me.

2018-05-30 20:09 UTC, puiterwijk commented on bodhi/server/buildsys.py
> +        raise NotImplementedError
Just to note: I've went for the dumb test method.

2018-06-01 19:02 UTC, bowlofeggs approved these changes

2018-06-01 19:02 UTC, merged

2018-07-13 12:07 UTC, bowlofeggs commented
This patch is planned to be included in the upcoming 3.9.0 release: #2477.