Avoid changing status to bugs which aren't related to approved products.
fedora-infra/bodhi pull request #2336
Opened 2018-04-28 08:38 UTC by mattiaverga

Fixes #1043 

Bodhi commments on bugs which are not Fedora or Fedora EPEL is still enabled since it's harmless. This however will only happen if the bug number is entered manually in the 'new update' form, since the javascript provides only Fedora and Epel bugs, or in the CLI. Or if a bug which was previously assigned to Fedora or Epel product has changed to something else during it's lifetime.

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

2018-05-03 21:32 UTC, bowlofeggs commented
jenkies test

2018-05-04 13:28 UTC, bowlofeggs requested changes
Cool, looks nice. We just need to get CI to be happy.

You've been sending quite a few PRs lately - if you think you'll be sending more, feel free to send a PR to add your name to [this list](https://github.com/fedora-infra/bodhi/blob/3.6.1/devel/ci/githubprb-project.yml#L6-L17) and Jenkies will automatically run the tests when you send PRs (no need to wait for an admin to type "jenkies test"). Thanks!

2018-05-04 13:28 UTC, bowlofeggs commented on bodhi/server/bugs.py
> +        and if it is not already ON_QA, VERIFIED, or CLOSED.
Bodhi uses [pydocstyle](http://www.pydocstyle.org) to enforce docblock style, and one of the rules it enforces is that the first paragraph of a docblock must be a single sentence.

```
f27	bodhi/server/bugs.py:166 in public method `on_qa`:
f27	        D205: 1 blank line required between summary line and description (found 0)
f27	bodhi/server/bugs.py:166 in public method `on_qa`:
f27	        D400: First line should end with a period (not 't')
```

To fix this, I suggest mentioning the product list restriction in its own paragraph. Perhaps something like this instead:

```
Change the status of this bug to ON_QA if it is not already ON_QA, VERIFIED, or CLOSED.

This method will only operate on bugs that are associated with products listed in the bz_products setting.
```

2018-05-04 13:28 UTC, bowlofeggs commented on bodhi/server/bugs.py
> +        mark it as fixed in the given versions, and add a comment.
Similar issue here:

```
f27	bodhi/server/bugs.py:191 in public method `close`:
f27	        D205: 1 blank line required between summary line and description (found 0)
f27	bodhi/server/bugs.py:191 in public method `close`:
f27	        D400: First line should end with a period (not ',')
```

2018-05-12 08:01 UTC, mattiaverga commented
jenkies test

2018-06-01 19:11 UTC, bowlofeggs approved these changes
Thanks!

2018-06-01 19:12 UTC, merged

2018-07-13 12:02 UTC, bowlofeggs commented
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

2018-08-20 16:57 UTC, pcahyna commented
Why does Bodhi close bugs that are against EPEL if the update is not for EPEL? See https://bugzilla.redhat.com/show_bug.cgi?id=1591906 . IIUC, the bz was mistakenly closed and gives now the impression that the issue was fixed in EPEL, while it is not.

2018-08-20 20:10 UTC, bowlofeggs commented
@pcahyna I think that's a separate (though related) issue - Bodhi does not have a mapping from releases to Bugzilla products. Feel free to file a new issue about that (or a PR!) if you like.

2018-08-21 06:26 UTC, mattiaverga commented
I think this is not yet fixed, since it's planned for 3.9.0?

2018-08-21 19:51 UTC, bowlofeggs commented
@mattiaverga correct, though I think the fix in 3.9.0 is also a bit different than what @pcahyna is discussing. The fix in 3.9.0 will assert that Bodhi doesn't edit bugs that aren't in EPEL or Fedora, but it will not assert that Fedora updates are not associated with EPEL bugs (or vice versa).

After thinking about it some more, I'm not sure such an enforcement would be popular with what I perceive as a common workflow - packagers often associate updates for EPEL with Fedora bugs if they make updates across all releases at once, and many people dislike cloning bugs in Fedora.

2018-08-22 15:03 UTC, mattiaverga commented
@bowlofeggs ah, I misunderstanded the problem.

I don't know how much hard can be to implement, but I was thinking about a general enforcement to check correspondence between Bugzilla product and Update builds.
I mean: if we have a bug opened on EPEL and a packager wants to associate an update in bugzilla, the update should carry at least one EPEL build. It doesn't make sense to have an update with builds for Fedora only that is associated to an EPEL bug (like the example reported), or an update with EPEL builds only which closes a Fedora bug.
Obviously, if the packager deploy in the same update a Fedora build and an EPEL build, the update can be associated with Fedora or EPEL products.

Shall we open a new bug for discussing more on that?

2018-08-22 17:10 UTC, bowlofeggs commented
@mattiaverga The problem is that a single Bodhi update cannot contain both EPEL and Fedora builds, because all builds in a Bodhi update must be for the same release.

2018-08-22 18:39 UTC, mattiaverga commented
@bowlofeggs ok, I'll try to explain my thoughts by example since it's more easy for me to write that in english.
Let's suppose that, from the web UI, I create a new update for 'package', I add builds for 'package.fc27', 'package.fc28' and 'package.el7'. I also add two related bugs, one is for component 'Fedora', the other for 'EPEL'.

Bodhi will now create three different updates, one for F27, one for F28 and one for EL7. But each update will be associated with both the bugs, so that the two Fedora updates will act also on the EPEL bug and viceversa.

In my opinion, bodhi lacks an enforcement when it splits the data from the user input to the three different updates. The EPEL bug should be associated to the EPEL update only, while the Fedora bug can be associated to both the Fedora updates (awful, but acceptable).

This would not break the packager common workflow, but it will help to keep things cleaner. There isn't any reason for a packager to fix an EPEL bug with a Fedora update, is there?

2018-08-22 18:59 UTC, bowlofeggs commented
On 08/22/2018 02:39 PM, Mattia Verga wrote:
> This would not break the packager common workflow, but it will help to
> keep things cleaner. There isn't any reason for a packager to fix an
> EPEL bug with a Fedora update, is there?

In my experience, the reverse happens quite often - packagers mark EPEL
bugs as fixing Fedora bugs. Most people don't clone bugs from Fedora to
EPEL even if they fix them there too, and some people are even morally
opposed to cloning bugs (@nirik ☺).

I haven't observed very many times when Fedora packages were marked as
fixing EPEL bugs, but I suppose that could happen too.

I personally think the current behavior is what packagers expect.

2018-08-22 19:08 UTC, pcahyna commented
> I personally think the current behavior is what packagers expect.

I certainly don't expect EPEL to carry a vulnerable package if the bug has been CLOSED/ERRATA, as it happened here. (I think the bug was not even matched by bz number but by a CVE id.)

2018-08-22 19:24 UTC, bowlofeggs commented
I agree that that particular bug being closed is bad.

Looking at the bug, it seems that [the packager was told to use a particular Bodhi template](https://bugzilla.redhat.com/show_bug.cgi?id=1591906#c1) when creating their update, and that template referenced that EPEL bug number. Thus, I don't think it was referenced by CVE ID in Bodhi.

If you feel strongly that Bodhi should refuse to cross-associate bugs, it could be helpful to get feedback from more Fedora packagers for additional perspectives. My position is based primarily on my perceptions of what people might expect, and perhaps additional feedback could be helpful to us. Perhaps a post on Fedora's devel list would be helpful?

Note that it isn't just EPEL vs. Fedora, but bugs can also be associated with particular versions of EPEL and Fedora.

2018-08-22 19:46 UTC, nirik commented
I'll note one case here that often causes me to be lazy about fedora vs epel bugs: If there's a security update and it affects both fedora and fedora epel, I build for all the needed branches, then use the web form to create seperate updates from that list. Since I am only filling in one update form I list both the fedora and fedora epel bug in there. If the code that splits things could be smart enough to attach fedora issues to fedora updates and epel issues to epel updates it would avoid that. Or I suppose if I was less lazy and did two updates forms.

2018-08-23 09:13 UTC, pcahyna commented
@bowlofeggs 
> Looking at the bug, it seems that the packager was told to use a particular Bodhi template when creating their update, and that template referenced that EPEL bug number. Thus, I don't think it was referenced by CVE ID in Bodhi.

The packager was told to do so when submitting an update for EPEL, but are you sure the suggested template has been ever used, given that the packager has apparently never submitted an update for EPEL? The bug (1591906) is listed among related bugs, and I wonder how it got there, was it by matching the CVE id or by explicit packager's decision?

Even if it was an explicit packager's decision, it appears to be a mistake and Bodhi should not honor the request.
 
@nirik 
> Since I am only filling in one update form I list both the fedora and fedora epel bug in there. If the code that splits things could be smart enough to attach fedora issues to fedora updates and epel issues to epel updates it would avoid that.

It sounds like the right thing to do.

> Or I suppose if I was less lazy and did two updates forms.

I would say the tool should save your time and allow you to be lazy.

2018-08-23 14:12 UTC, bowlofeggs commented
@pcahyna I cannot be sure what the packager did, but the OP for that BZ did tell the packager to associate their updates with that bug via the template pasted. If the packager followed those instructions, that would explain how this happened.

In any case, I still invite you to start a discussion on Fedora devel, or even file a new issue about this. This pull request isn't a great forum for discussing this since it's technically not about this issue and since it's not discoverable by others (since it's merged).

2018-08-28 16:51 UTC, bowlofeggs commented
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.