Add support to filter releases by state in the JSON API
fedora-infra/bodhi pull request #2484
Opened 2018-07-18 07:21 UTC by cverna

This will be useful for fedora-packages to get the list of 'active' releases . Currently it is getting all the releases and checking the state attribute of each release.

2018-07-18 09:31 UTC, pypingou submitted a review, later dismissed

2018-07-24 19:05 UTC, bowlofeggs requested changes
Looks good, just a stray print statement to drop and we should be good.

2018-07-24 19:05 UTC, bowlofeggs commented on bodhi/tests/server/services/test_releases.py
> +        print(len(body['releases']))
Let's drop this print statement.

2018-07-25 06:39 UTC, cverna commented
Updated :sake:

2018-07-25 19:32 UTC, bowlofeggs approved these changes

2018-07-26 21:34 UTC, bowlofeggs commented
jenkies test

2018-07-26 23:10 UTC, merged

2018-08-28 17:33 UTC, bowlofeggs commented
These patches are planned to be included in the upcoming 3.10.0 release: #2556.

2018-08-31 16:40 UTC, bowlofeggs commented
These patches have been deployed to Fedora's staging Bodhi instance:

https://bodhi.stg.fedoraproject.org/