Add a ComposeState for _wait_for_sync()
fedora-infra/bodhi pull request #2605
Opened 2018-09-17 17:00 UTC by mattiaverga

Fix #2550 

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

2018-09-18 22:38 UTC, bowlofeggs requested changes
Nice! This looks pretty good. The only thing we still need that I can think of is a database migration to extend the enum. There are a couple migrations that do something like this already that you can base your migration off of, for example:

https://github.com/fedora-infra/bodhi/blob/3.10.0/bodhi/server/migrations/versions/2c5d45f0c932_add_a_new_state_for_cleaning_composes.py

You can use alembic to start the template for you like this:

```
$ alembic revision --autogenerate -m "Add a syncing_repo ComposeState enum value."
```

2018-09-19 16:29 UTC, mattiaverga commented
I've added the `syncing_repo` value after `punging` instead at the end of the list to maintain the order specified in the docstring (where I added it in the right point of the sequence).
I'm totally new to alembic, but running the upgrade locally returned no errors, so I think it's ok...

2018-09-20 16:58 UTC, mattiaverga commented
jenkies test

2018-09-28 20:34 UTC, bowlofeggs requested changes
Looks great - just need you to claim copyright on your migration and we should be good to merge.

2018-09-28 20:34 UTC, bowlofeggs commented on bodhi/server/migrations/versions/68f9ccb1f388_add_a_syncing_repo_composestate_enum_.py
> +# Copyright (c) YEAR AUTHOR
Let's fill in the year and author:

```
# Copyright (c) 2018 Mattia Verga
```

2018-09-28 20:36 UTC, bowlofeggs commented on bodhi/server/migrations/versions/68f9ccb1f388_add_a_syncing_repo_composestate_enum_.py
> +# Copyright (c) YEAR AUTHOR
This is a minor enough of a change that I'll just force push your branch and fix it for you. Fix incoming!

2018-09-28 20:39 UTC, bowlofeggs submitted a review, later dismissed

2018-10-02 13:54 UTC, bowlofeggs commented
jenkies test

2018-10-02 18:05 UTC, bowlofeggs approved these changes

2018-10-02 21:21 UTC, bowlofeggs commented
jenkies test

2018-10-03 13:09 UTC, bowlofeggs commented
Mergify seems stuck, so I'm going to manually rebase and merge this one.

2018-10-03 13:09 UTC, merged