Document the composes and releases subcommands in man page.
fedora-infra/bodhi pull request #2642
Opened 2018-10-04 21:49 UTC by bowlofeggs

The high level overview in the man page was missing documentation
about the composes and releases subcommands.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

2018-10-05 07:44 UTC, Zlopez requested changes
Missing the `composes` section, otherwise it looks good.

2018-10-05 07:44 UTC, Zlopez commented on docs/user/man_pages/bodhi.rst
> +``bodhi composes <subcommand> [options] [args]``
I don't see the composes command anywhere in this man page. There is section for `overrides`, `releases` and `updates`. But no section for `composes`.

2018-10-05 18:21 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +``bodhi composes <subcommand> [options] [args]``
Heh, so you are right. I thought I had done that before but apparently not. I'll write that up now.

2018-10-05 18:26 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +``bodhi composes <subcommand> [options] [args]``
@Zlopez I have added docs on the compose command now.

2018-10-05 19:25 UTC, Zlopez approved these changes

2018-10-05 20:11 UTC, cverna approved these changes
+1

2018-10-05 20:39 UTC, merged

2018-10-05 20:39 UTC, bowlofeggs commented
The Rawhide failure is due to https://bugzilla.redhat.com/show_bug.cgi?id=1636611 and can be ignored.

2018-11-06 18:47 UTC, bowlofeggs commented
This feature is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

2018-11-12 16:59 UTC, bowlofeggs commented
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release

2018-11-19 21:06 UTC, bowlofeggs commented
This feature is now released with 3.11.0.