Add pagination to docs
fedora-infra/bodhi pull request #2663
Opened 2018-10-12 21:18 UTC by sebwoj

Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

2018-10-15 13:12 UTC, Zlopez submitted a review, later dismissed
LGTM

2018-10-23 20:49 UTC, bowlofeggs commented
I'm going to rebase and force push this.

2018-10-23 20:55 UTC, bowlofeggs requested changes
The new options render inconsistently with the existing options due to indentation. It's an easy fix - I'll fix and push to your branch. Thanks for the patch!

2018-10-23 20:55 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +      ``--rows <integer>``
```suggestion
    ``--rows <integer>``
```

2018-10-23 20:55 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +      ``--page <integer>``
```suggestion
    ``--page <integer>``
```

2018-10-23 20:55 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +      ``--rows <integer>``
```suggestion
    ``--rows <integer>``
```

2018-10-23 20:55 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +      ``--page <integer>``
```suggestion
    ``--page <integer>``
```

2018-10-23 20:59 UTC, bowlofeggs commented
I'm going to apply this patch to your branch:

```
diff --git a/docs/user/man_pages/bodhi.rst b/docs/user/man_pages/bodhi.rst
index 1430170f..c8b694c7 100644
--- a/docs/user/man_pages/bodhi.rst
+++ b/docs/user/man_pages/bodhi.rst
@@ -133,11 +133,11 @@ The ``overrides`` command allows users to manage build overrides.

         Filter for overrides by a list of usernames, given as a comma-separated list.

-      ``--rows <integer>``
+    ``--rows <integer>``

         Limits number of results shown per page.

-      ``--page <integer>``
+    ``--page <integer>``

         Go to page number.

@@ -425,11 +425,11 @@ The ``updates`` command allows users to interact with bodhi updates.

         Filter for updates by a list of usernames, given as a comma-separated list.

-      ``--rows <integer>``
+    ``--rows <integer>``

         Limits number of results shown per page.

-      ``--page <integer>``
+    ``--page <integer>``

         Go to page number.
```

2018-10-23 21:01 UTC, bowlofeggs approved these changes

2018-10-23 21:27 UTC, merged

2018-11-06 18:47 UTC, bowlofeggs commented
This feature is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

2018-11-12 17:00 UTC, bowlofeggs commented
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release