Give bodhi push a y flag
fedora-infra/bodhi pull request #2664
Opened 2018-10-13 15:00 UTC by sebwoj

fixed #2635

2018-10-15 13:17 UTC, Zlopez commented
Shouldn't we just set `resume_all` and `resume` to `True` when `y` flag is added?

2018-10-23 21:30 UTC, bowlofeggs requested changes
Cool, looks great! I'm going to change the flag to be ```--yes/-y``` instead of ```--y``` due to the convention of single-letter flags only using a single ```-```. I'll fix that, rebase your branch, and squash your commits and it should be good to merge. Thanks!

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/server/push.py
> +@click.option('--y', is_flag=True, default=False, help='Answers yes to the various questions')
```suggestion
@click.option('--yes/-y', is_flag=True, default=False, help='Answers yes to the various questions')
```

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/server/push.py
> +def push(username, cert_prefix, y, **kwargs):
```suggestion
def push(username, cert_prefix, yes, **kwargs):
```

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/server/push.py
> +    resume = kwargs.pop('resume') or y
```suggestion
    resume = kwargs.pop('resume') or yes
```

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/server/push.py
> +    resume_all = False or y
```suggestion
    resume_all = False or yes
```

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/server/push.py
> +            if y:
```suggestion
            if yes:
```

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/tests/server/test_push.py
> +        Test correct operation when there are some locked updates and --y flag is given.
```suggestion
        Test correct operation when there are some locked updates and -y flag is given.
```

2018-10-23 21:30 UTC, bowlofeggs commented on bodhi/tests/server/test_push.py
> +            result = cli.invoke(push.push, ['--username', 'bowlofeggs', '--y'])
```suggestion
            result = cli.invoke(push.push, ['--username', 'bowlofeggs', '-y'])
```

2018-10-23 22:36 UTC, bowlofeggs commented
I'm applying this patch:

```
diff --git a/bodhi/server/push.py b/bodhi/server/push.py
index eca71623..455ed879 100644
--- a/bodhi/server/push.py
+++ b/bodhi/server/push.py
@@ -61,12 +61,12 @@ def update_sig_status(update):
 @click.option('--resume', help='Resume one or more previously failed pushes',
               is_flag=True, default=False)
 @click.option('--username', prompt=True)
-@click.option('--y', is_flag=True, default=False, help='Answers yes to the various questions')
+@click.option('--yes/-y', is_flag=True, default=False, help='Answers yes to the various questions')
 @click.version_option(message='%(version)s')
-def push(username, cert_prefix, y, **kwargs):
+def push(username, cert_prefix, yes, **kwargs):
     """Push builds out to the repositories."""
-    resume = kwargs.pop('resume') or y
-    resume_all = False or y
+    resume = kwargs.pop('resume') or yes
+    resume_all = False or yes

     initialize_db(config)
     db_factory = transactional_session_maker()
@@ -149,7 +149,7 @@ def push(username, cert_prefix, y, **kwargs):
                 click.echo(update.title)

         if composes:
-            if y:
+            if yes:
                 click.echo('\n\nPushing {:d} updates.'.format(
                     sum([len(c.updates) for c in composes])))
             else:
diff --git a/bodhi/tests/server/test_push.py b/bodhi/tests/server/test_push.py
index 4fed04f8..955c82d3 100644
--- a/bodhi/tests/server/test_push.py
+++ b/bodhi/tests/server/test_push.py
@@ -489,7 +489,7 @@ class TestPush(base.BaseTestCase):
     @mock.patch('bodhi.server.push.bodhi.server.notifications.publish')
     def test_locked_updates_y_flag(self, publish, mock_init):
         """
-        Test correct operation when there are some locked updates and --y flag is given.
+        Test correct operation when there are some locked updates and -y flag is given.
         """
         cli = CliRunner()
         # Let's mark ejabberd as locked and already in a push. bodhi-push should resume this
@@ -505,7 +505,7 @@ class TestPush(base.BaseTestCase):

         with mock.patch('bodhi.server.push.transactional_session_maker',
                         return_value=base.TransactionalSessionMaker(self.Session)):
-            result = cli.invoke(push.push, ['--username', 'bowlofeggs', '--y'])
+            result = cli.invoke(push.push, ['--username', 'bowlofeggs', '--yes'])

         self.assertEqual(result.exit_code, 0)
         mock_init.assert_called_once_with(active=True, cert_prefix=u'shell')
```

2018-10-24 14:57 UTC, bowlofeggs commented
Ah, and apparently I didn't express the ```--yes``` and ```-y``` flags meaning the same thing correctly, here's another patch I'm applying:

```
diff --git a/bodhi/server/push.py b/bodhi/server/push.py
index 455ed879..f2262c0b 100644
--- a/bodhi/server/push.py
+++ b/bodhi/server/push.py
@@ -61,7 +61,8 @@ def update_sig_status(update):
 @click.option('--resume', help='Resume one or more previously failed pushes',
               is_flag=True, default=False)
 @click.option('--username', prompt=True)
-@click.option('--yes/-y', is_flag=True, default=False, help='Answers yes to the various questions')
+@click.option('--yes', '-y', is_flag=True, default=False,
+              help='Answers yes to the various questions')
 @click.version_option(message='%(version)s')
 def push(username, cert_prefix, yes, **kwargs):
     """Push builds out to the repositories."""
```

2018-10-24 15:00 UTC, bowlofeggs requested changes
This doesn't seem to work as I would expect. When I run ```bodhi-push``` without the ```-y``` flag, I am prompted to push a bunch of updates:

```
[vagrant@bodhi-dev bodhi]$ bodhi-push --username bowlofeggs
<snip>
Push these 230 updates? [y/N]:
```

When I run it with ```--yes```, I see this:

```
[vagrant@bodhi-dev bodhi]$ bodhi-push --username bowlofeggs --yes                               
There are no updates to push.
```

2018-10-25 09:54 UTC, Zlopez commented
This looks like they aren't any composes found when `--yes` is provided, which is strange.

2018-10-30 16:36 UTC, bowlofeggs commented
Excellent, this seems to work now. The f28-build failure is not because of this PR - I will rebase your PR to see if re-running CI gets that to work.

2018-10-30 16:51 UTC, bowlofeggs approved these changes

2018-10-30 17:04 UTC, merged