Gracefully handle private bugs
fedora-infra/bodhi pull request #2714
Opened 2018-11-07 10:27 UTC by mattiaverga

The PR adds a new column to bugs table to flag as private those bugs which are not publicly accessible in RH BZ.
Bodhi will avoid to comment or change status of those bugs, since it doesn't have permission to do so. Those bugs can still be attached to updates as reference for maintainer and to allow the reporter to give feedback. In the GUI they will be displayed with a "Private bug" label, and the same string will be used for title (as Bodhi can't fetch the real title).

This comes with all relevant tests, but I couldn't test in real, because in the vagrant box all users are granted only the 'guest' permissions.

This PR involves change in database schema.
Fixes #344 

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

2018-11-08 08:00 UTC, mattiaverga commented
JENKIES TEST

2018-11-08 08:05 UTC, mattiaverga commented
JENKINS TEST

2018-12-04 15:53 UTC, bowlofeggs requested changes

2018-12-04 15:53 UTC, bowlofeggs commented on bodhi/server/consumers/updates.py
> +        If the bug is private, Bodhi can't retrieve any information, neither comment it or modify
```suggestion
        If the bug is private, Bodhi can't retrieve any information, comment on it, or modify
```

2018-12-04 15:53 UTC, bowlofeggs commented on bodhi/server/consumers/updates.py
> +        it, so we just associate the bug id to the update and mark it to be private.
```suggestion
        it, so we just associate the bug id with the update and mark it to be private.
```

2018-12-04 15:53 UTC, bowlofeggs commented on bodhi/server/mail.py
> +                    and bug.title != 'Private bug') \
```suggestion
                    and not bug.private) \
```

Also, ```flake8``` is not happy with these lines:

```
04:25:11 ./bodhi/server/mail.py:329:21: W503 line break before binary operator
04:25:11                     and bug.title != 'Invalid bug number'
04:25:11                     ^
04:25:11 ./bodhi/server/mail.py:329:21: E128 continuation line under-indented for visual indent
04:25:11                     and bug.title != 'Invalid bug number'
04:25:11                     ^
04:25:11 ./bodhi/server/mail.py:330:21: W503 line break before binary operator
04:25:11                     and bug.title != 'Private bug') \
04:25:11                     ^
04:25:11 ./bodhi/server/mail.py:330:21: E128 continuation line under-indented for visual indent
04:25:11                     and bug.title != 'Private bug') \
```

2018-12-04 15:53 UTC, bowlofeggs commented on bodhi/server/migrations/versions/3a14c47250fb_add_a_private_flag_to_bugs.py
> +    op.alter_column('bugs', 'private', nullable=False, server_default='false')
Let's let the Python models deal with defaults instead of the server.

```suggestion
    op.alter_column('bugs', 'private', nullable=False)
```

2018-12-05 17:50 UTC, mattiaverga commented
mmm it seems flake8 doesn't like line breaks before binary operator nor after:
```
./bodhi/server/mail.py:328:26: W504 line break after binary operator
                title = (bug.title != 'Unable to fetch title' and
                         ^
```
```
bodhi/server/mail.py:329:26: W503 line break before binary operator
                         and bug.title != 'Invalid bug number'
                         ^
```
Searching around it seems [PEP-8](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) recently changed the best practice to be line break before binary operator, so I will change the code to do so. Probably we need to disable W503 error check in flake8.

2018-12-07 15:18 UTC, bowlofeggs commented
Yeah let's break before as recommended by PEP-8. If we need to disable that warning to get it to accept that, so be it, though it would be good to file an issue with ```flake8``` about this.

2018-12-07 16:35 UTC, mattiaverga commented
>  it would be good to file an issue with `flake8` about this.

It seems that someone already did it and the reply was "add w503 to --ignore"... 
https://gitlab.com/pycqa/flake8/issues/463

May I add that setting myself in this same PR, but in a separate commit?

2018-12-07 17:01 UTC, mattiaverga commented
More on this: the best solution would be to change `ignore` to `extend-ignore`, which would not overwrite flake8 defaults. Unfortunately, `extend-ignore` was introduced in version 3.6, which is not yet available in Fedora repositories (devel environment seems to use 3.4.1).

BTW is there any compelling reason to ignore E712?
```
./bodhi/server/models.py:2296:36: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
                     Update.locked == False,
                                   ^
./bodhi/server/views/generic.py:84:36: E712 comparison to True should be 'if cond is True:' or 'if cond:'
            models.Update.critpath == True)
                                   ^
```

2018-12-07 18:31 UTC, bowlofeggs commented
On Fri, 2018-12-07 at 08:35 -0800, Mattia Verga wrote:
> It seems that someone already did it and the reply was "add w503 to
> --ignore"...
> https://gitlab.com/pycqa/flake8/issues/463

Ha, that's so strange.

> May I add that setting myself in this same PR, but in a separate
> commit?

Sure, and thanks!

2018-12-07 18:35 UTC, bowlofeggs commented
On Fri, 2018-12-07 at 09:01 -0800, Mattia Verga wrote:
> More on this: the best solution would be to change ignore to extend-
> ignore, which would not overwrite flake8 defaults. Unfortunately,
> extend-ignore was introduced in version 3.6, which is not yet
> available in Fedora repositories (devel environment seems to use
> 3.4.1).

Since flake8 is only used by CI and Vagrant, I think it's OK for us to
pip install a newer version if you want, instead of using the RPM. The
downstream spec file does not run flake8, so it really is just used by
us here.

I'll make myself a todo to send a PR to the python-flake8 package to
get it updated and switch our Rawhide back to the RPM when that is
done.

> BTW is there any compelling reason to ignore E712?
> ./bodhi/server/models.py:2296:36: E712 comparison to False should be
> 'if cond is False:' or 'if not cond:'
>                      Update.locked == False,
>                                    ^
> ./bodhi/server/views/generic.py:84:36: E712 comparison to True should
> be 'if cond is True:' or 'if cond:'
>             models.Update.critpath == True)
>                                    ^

Not really - I think I just was lazy. I did not know if sqlalchemy
works with the is operator and just hadn't taken the time to
investigate.

2018-12-10 16:35 UTC, mattiaverga commented
For now I've simply added W503 to the `exclude` list.
When flake8 3.6 will be available we can simply correct those two E712 and get rid of the entire `exclude` line, since W503 will be ignored by default.

2018-12-10 22:38 UTC, bowlofeggs commented
The ```f29-python3-unit``` test actually passed but CI failed while notifying GitHub about it, seemingly. I suspect the integration test failure is due to https://github.com/fedora-infra/bodhi/issues/2835

2018-12-10 22:44 UTC, bowlofeggs approved these changes
Thanks!

2018-12-11 14:56 UTC, bowlofeggs commented
Ah, looks like there's a conflict - I'll rebase and fix that for you.

2018-12-11 15:33 UTC, merged

2019-01-10 19:52 UTC, bowlofeggs commented
This feature is planned for inclusion in Bodhi 3.13: #2917.

2019-01-17 09:49 UTC, bowlofeggs commented
This feature is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

2019-02-15 19:57 UTC, bowlofeggs commented
Bodhi 3.13.0 has been released:

https://github.com/fedora-infra/bodhi/releases/tag/3.13.0

Fedora Infrastructure plans to deploy it to production on Monday.