Disallow null values in stable_karma and unstable_karma.
fedora-infra/bodhi pull request #2971
Opened 2019-02-02 12:56 UTC by sebwoj

Fixes #1029

Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

2019-02-07 19:30 UTC, bowlofeggs requested changes
This change does a little bit more than disallowing ```NULL``` values as it also removes the meaning of having the karma values set to ```0```.

That said, I'm not sure what use case there really would be for setting it to ```0```. We do have the ```autokarma``` bool to select whether updates push when they reach a karma threshold, so it seems a little odd to also give ```0``` the meaning of not having Bodhi comment on updates, but that's what the current code seems to do.

I wonder if we should start a discussion on fedora-devel to ask if anyone uses a value of 0 and why. That might give us more confidence in removing it.

2019-02-07 19:30 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +    click.option('--unstable-karma', type=click.INT, help='Unstable karma threshold', default=-3),
I think it's better to enforce the defaults server-side like we were doing before.

2019-02-08 11:36 UTC, sebwoj commented
I think that it is impossible to set stable/unstable karma to 0:
https://github.com/fedora-infra/bodhi/blob/ceff3c7a0fc7bf4913b5566d4623bbd43e25e74c/bodhi/server/schemas.py#L213

2019-02-08 11:36 UTC, sebwoj commented
Unintentionally closed...

2019-03-08 17:57 UTC, bowlofeggs approved these changes
Thanks!

2019-03-08 17:59 UTC, bowlofeggs commented
Ah, that conflict is likely due to the other patch that renamed the file - I'll fix it up for you!

2019-03-08 20:26 UTC, bowlofeggs commented
Looks like the DB timed out in that CI test. I think https://github.com/fedora-infra/bodhi/pull/3054 will help with that. I'll manually test and merge this one.

2019-03-08 20:42 UTC, merged

2019-05-08 13:58 UTC, bowlofeggs commented
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

2019-05-10 17:44 UTC, bowlofeggs commented
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/