Store critical path packages in bodhi.
fedora-infra/bodhi pull request #3049
Opened 2019-02-28 11:21 UTC by cverna

This commit add support to associate a list of critical path packages
to a release. This commit adds a simple API that allow a use to GET or
to set (POST) the list of critical path packages.

Co-authored-by: Vismay Golwala <vgolwala@redhat.com>
Co-authored-by: Clement Verna <cverna@tutanota.com>

Signed-off-by: Clement Verna <cverna@tutanota.com>

---

Support to bodhi client will be added in a following PR to make this easier to review. Let me know if you  prefer to have everything in one PR.

2019-03-07 08:37 UTC, cverna commented
jenkies test

2019-03-13 21:15 UTC, bowlofeggs requested changes

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +    [PACKAGES]: comma separated list of packages to add (e.g. firefox,vim,python)
How many critpath packages do you think we have, approximately? I wonder if this will be a burdensome way to add/remove them. I also wonder if we will hit the max length of shell arguments?

The alternative might also be burdensome, however, which would be to have add/remove commands. Unless maybe the add/remove commands still at least support comma separated lists like is done here?

I guess my main concern is whether we will hit the shell limits or not. I don't have a super convenient way to find out which packages are critical path. Bodhi's database has a bool on whether an *update* is critical path, but that's not a direct way to answer the question. We could probably query PDC to find out, though I think it's data is also not up to date.

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +    [PACKAGES]: comma separated list of packages to add (e.g. firefox,vim,python)
I also recognize that this is how the releng script works.

One option we could consider is giving the bindings the ability to set critpath packages, like this here, and then just use that in the releng script. We could leave this code for other Bodhi deployments to use, if they want. Then we at least know that Fedora won't hit shell limits.

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/client/bindings.py
> +            dict: A dictionary returned by critpath_package_requests() method.
I haven't documented this yet (it's on my todo list), but I plan to change Bodhi's contributor docs to formally state that we should use type hinting instead of this doc style for documenting types. It's OK to leave this here since I haven't actually done that yet, I'm more letting you know for future patches in Bodhi. Hopefully I'll find the time to write that up soon. (Really, this is fine, and it'll be useful when I come through later and add type hinting ☺)

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/client/bindings.py
> +            raise BodhiClientException("Unsupported request type.")
We could also use a ```ValueError``` here instead.

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/client/bindings.py
> +            'releases/{}/critpath'.format(release), verb=verb, auth=auth, data=data
We can use f-strings, now that we are finally Python 3 only!

```suggestion
            f'releases/{release}/critpath', verb=verb, auth=auth, data=data
```

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/server/migrations/versions/a96dadf085c2_add_critcal_path_packages.py
> +down_revision = '8c4d6aad9b78'
This likely needs to be updated, as I merged some commits today with migrations. As of the time of this writing, the head is ```58b7919b942c```.

```suggestion
down_revision = '58b7919b942c'
```

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/server/migrations/versions/a96dadf085c2_add_critcal_path_packages.py
> +Revises: 8c4d6aad9b78
```suggestion
Revises: 58b7919b942c
```

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/server/migrations/versions/a96dadf085c2_add_critcal_path_packages.py
> +        sa.ForeignKeyConstraint(['release_id'], ['releases.id'], )
It would be a good idea to add an index to these columns - PostgreSQL does not automatically index foreign key constraints.

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/server/models.py
> +    Column('release_id', Integer, ForeignKey('releases.id'), nullable=False)
Also here - good idea to add indices.

In general, I think a lot of Bodhi's slowness issues could be solved if we did an analysis on the queries we run and added indices. It's been on my todo list for like 3 years.

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/client/__init__.py
> +    [PACKAGES]: comma separated list of packages to add (e.g. firefox,vim,python)
All of the above to say, I'm fine with doing it this way as long as we have the releng script use the bindings instead of shelling out to this, or as long as we think the list is short enough that we don't have to worry. Either way, I'm happy to merge this ☺

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/server/validators.py
> +        except Exception:
Let's catch the expected Exception type here instead of all Exceptions.

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/server/validators.py
> +                "Invalid packages specified: {}".format(", ".join(bad_packages))
```suggestion
                f"Invalid packages specified: {", ".join(bad_packages)}"
```

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/tests/server/services/test_releases.py
> +
For PEP-8:

```suggestion
```

2019-03-13 21:15 UTC, bowlofeggs commented on bodhi/tests/server/services/test_releases.py
> +
PEP-8:

```suggestion
```

2019-03-14 10:23 UTC, cverna commented on bodhi/client/__init__.py
> +    [PACKAGES]: comma separated list of packages to add (e.g. firefox,vim,python)
So looking at pdc there are 756 critical path packages for f29 (https://pdc.fedoraproject.org/rest_api/v1/component-branches/?active=true&critical_path=true&name=f29). So yes passing this into the shell might not be super smart :)

The current releng script takes a .txt file as an entry, what do you think about doing the same for the bodhi client ?

2019-03-21 18:18 UTC, bowlofeggs requested changes
There are some pydocstyle and unit test failures.

The pydocstyle failures are these:

```
 bodhi/client/__init__.py:1222 in public function `print_critpath_packages`:
         D202: No blank lines allowed after function docstring (found 1)
 bodhi/server/migrations/versions/a429f263fc3f_add_critical_path_packages.py:1 at module level:
         D400: First line should end with a period (not 's')
 bodhi/server/migrations/versions/a429f263fc3f_add_critical_path_packages.py:34 in public function `upgrade`:
         D103: Missing docstring in public function
 bodhi/server/migrations/versions/a429f263fc3f_add_critical_path_packages.py:56 in public function `downgrade`:
         D103: Missing docstring in public function
      f28-build                      :  SKIPPED
      f28-pydocstyle                 :  FAILED    [0:00:24.480490] (exited with code: 1)
```

The unit test failures seem to be due to https://github.com/fedora-infra/python-fedora/pull/213 not being available for the code to use.

2019-04-29 16:47 UTC, bowlofeggs commented
Closing due to inactivity.

2019-04-29 16:47 UTC, closed without merging