Mitigate one kitchen overuse
fedora-infra/bodhi pull request #3072
Opened 2019-03-20 00:44 UTC by hroncok

This function converted a fixed unicode character to itself

Signed-off-by: Miro Hrončok <miro@hroncok.cz>

2019-03-20 07:48 UTC, sebwoj requested changes

2019-03-20 07:48 UTC, sebwoj commented on bodhi/tests/server/test_mail.py
> +        self.assertTrue('\xe7' in t)
I recommend `assertIn` here.

2019-03-20 10:16 UTC, hroncok commented
Should I worry about the CI? This could not have possibly caused breakage in integration tests.

2019-03-20 10:17 UTC, hroncok commented on bodhi/tests/server/test_mail.py
> +        self.assertTrue('\xe7' in t)
```suggestion
        self.assertIn('\xe7', t)
```

2019-03-20 10:19 UTC, hroncok commented
Note: If I use the suggestions feature on GitHub, the DCO thing breaks. Off to a terminal.

2019-03-20 16:28 UTC, hroncok commented
https://github.com/fedora-infra/bodhi/issues/3074

2019-03-22 14:01 UTC, bowlofeggs approved these changes
Thanks for the patch! I'm going to squash it to one commit and merge.

2019-03-22 14:01 UTC, bowlofeggs commented on bodhi/tests/server/test_mail.py
> -        self.assertTrue(converters.to_unicode('\xe7') in t)
Haha, kitchen is so bad.

2019-03-22 14:01 UTC, merged