Spelling
fedora-infra/bodhi pull request #3131
Opened 2019-04-05 04:47 UTC by jsoref

Most of these changes should be non-controversial. I'll try to call out the ones that have more risk...

2019-04-05 04:55 UTC, jsoref commented on bodhi/server/config.py
> +            'value': ['proventesters', 'security_response', 'bodhiadmin', 'sysadmin-main'],
It's possible this is tied to a database and thus this change could be problematic. Dropping this commit is easily done.

2019-04-05 04:55 UTC, jsoref commented on bodhi/server/ffmarkdown.py
> +        md.postprocessors.add('surround', SurroundProcessor(md), '_end')
It's possible this is intentionally matching `surrond`. If that's the case, it'd be a good idea to add a comment here.

2019-04-05 04:55 UTC, jsoref commented on production.ini
> +# When a user logs in, bodhi will look for any of these groups and associate
I'm not sure what the story is here... It was part of the original. It isn't technically a spelling fix, I can certainly split this off if requested...

2019-04-05 20:03 UTC, jsoref commented on bodhi/server/config.py
> +            'value': ['proventesters', 'security_response', 'bodhiadmin', 'sysadmin-main'],
practically speaking this can't be changed w/ FAS as it exists today, but this fact can be documented: #3133

2019-04-05 20:04 UTC, jsoref commented on bodhi/server/ffmarkdown.py
> +        md.postprocessors.add('surround', SurroundProcessor(md), '_end')
Since this is likely to require discussion / to simplify reviews, I've moved it to #3134

2019-04-15 21:35 UTC, bowlofeggs requested changes
Cool, thanks so much! I'm going to squash all commits except for the first, fix the two little issues I commented on, resolve the merge conflict, and then mark for approval.

2019-04-15 21:35 UTC, bowlofeggs commented on docs/user/man_pages/bodhi.rst
> +        A comma=separated list of update IDs you would like to download.
```suggestion
        A comma-separated list of update IDs you would like to download.
```

2019-04-15 21:35 UTC, bowlofeggs commented on bodhi/tests/server/test_config.py
> +        """Test we log an error if get_configfile() doesnt find a config file"""
```suggestion
        """Test we log an error if get_configfile() doesn't find a config file"""
```

2019-04-15 21:44 UTC, bowlofeggs approved these changes

2019-04-16 14:47 UTC, bowlofeggs commented
Ah, looks like flake8 is unhappy about a few spots:

https://ci.centos.org/job/bodhi-pipeline/job/PR-3131/7/execution/node/322/log/

I'll fix that up too.

2019-04-16 17:04 UTC, bowlofeggs commented
Ugh, GitHub API limits again. I'll run tests locally and merge if they pass.

2019-04-16 18:06 UTC, merged

2019-05-08 15:00 UTC, bowlofeggs commented
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

2019-05-10 17:41 UTC, bowlofeggs commented
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/