Refactor and rename the met_testing_requirements function.
fedora-infra/bodhi pull request #3158
Opened 2019-04-16 19:43 UTC by cverna

The met_testing_requirements function is really only used to check
if bodhi has already commented on the update that the requirements
have been met. This commit renames the function and remove duplicated
logic.

Signed-off-by: Clement Verna <cverna@tutanota.com>

2019-05-01 15:18 UTC, bowlofeggs approved these changes
Thanks, this is much cleaner!

2019-05-01 15:18 UTC, bowlofeggs commented
I will rebase to resolve the conflict.

2019-05-01 15:43 UTC, sebwoj requested changes

2019-05-01 15:43 UTC, sebwoj commented on bodhi/server/models.py
> +        Return whether or bodhi has commented on the update that the requirements have been met.
Let's remove 'or' from this sentence.

2019-05-01 16:00 UTC, bowlofeggs commented on bodhi/server/models.py
> +        Return whether or bodhi has commented on the update that the requirements have been met.
+1, I'll apply:

```
diff --git a/bodhi/server/models.py b/bodhi/server/models.py
index 87d37a28..423849c6 100644
--- a/bodhi/server/models.py
+++ b/bodhi/server/models.py
@@ -3323,7 +3323,7 @@ class Update(Base):
     @property
     def has_stable_comment(self):
         """
-        Return whether or bodhi has commented on the update that the requirements have been met.
+        Return whether Bodhi has commented on the update that the requirements have been met.
 
         This is used to determine whether bodhi should add the comment
         about the Update's eligibility to be pushed, as we only want Bodhi
```

2019-05-01 16:00 UTC, bowlofeggs commented
Heh, the test failures are due to my rebase - I'll fix that up too.

2019-05-01 16:14 UTC, bowlofeggs commented
This should fix it:

```
diff --git a/bodhi/server/models.py b/bodhi/server/models.py
index 87d37a28..423849c6 100644
--- a/bodhi/server/models.py
+++ b/bodhi/server/models.py
@@ -3323,7 +3323,7 @@ class Update(Base):
     @property
     def has_stable_comment(self):
         """
-        Return whether or bodhi has commented on the update that the requirements have been met.
+        Return whether Bodhi has commented on the update that the requirements have been met.
 
         This is used to determine whether bodhi should add the comment
         about the Update's eligibility to be pushed, as we only want Bodhi
```

2019-05-01 19:59 UTC, bowlofeggs commented
Hmm, we seem to have a repeatable [dnf failure](https://ci.centos.org/job/bodhi-pipeline/job/PR-3158/4/execution/node/194/log/):

```
14:50:45  error: rpmdb: BDB0689 Packages page 3008 is on free list with type 7
14:50:45  error: rpmdb: BDB0061 PANIC: Invalid argument
14:50:45  error: db5 error(-30973) from dbcursor->c_put: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
14:50:45  error: error(-30973) adding header #546 record
14:50:45  error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
14:50:45  error: db5 error(-30973) from db->sync: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
```

See also #3145.

2019-05-01 20:46 UTC, bowlofeggs commented
I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1705265 about the rpmdb corruption issue.

2019-05-01 21:32 UTC, bowlofeggs commented
I've opened https://github.com/fedora-infra/bodhi/pull/3207 to work around https://bugzilla.redhat.com/show_bug.cgi?id=1705265

2019-05-02 03:27 UTC, merged

2019-05-08 15:03 UTC, bowlofeggs commented
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

2019-05-10 17:43 UTC, bowlofeggs commented
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/