Add ctype to the ComposeComplete
fedora-infra/bodhi pull request #3329
Opened 2019-06-19 11:50 UTC by Zlopez

Fixes #3297

Signed-off-by: Michal Konečný <mkonecny@redhat.com>

2019-06-19 15:49 UTC, nphilipp approved these changes
LGTM, thanks!

2019-06-19 15:49 UTC, nphilipp commented on bodhi/messages/schemas/compose.py
> +                'description': 'Type of the compose'
I'd add a period to the end, for consistency (see above descriptions).

2019-06-19 15:52 UTC, nphilipp requested changes
Gah, forgot: please squash the commits into one.

2019-06-20 07:17 UTC, Zlopez commented on bodhi/messages/schemas/compose.py
> +                'description': 'Type of the compose'
Fixed

2019-06-20 07:18 UTC, Zlopez commented
Squashed commits

2019-06-20 15:36 UTC, nphilipp approved these changes
Great, thanks!

2019-06-21 07:43 UTC, merged