Query Greenwave in batches to avoid timeouts
fedora-infra/bodhi pull request #3380
Opened 2019-07-12 07:04 UTC by hluk

Asking Greenwave service to make decision about too many builds (in an
update) can result in the request timing out.

Instead, this big request can be split into smaller ones, each with a
limited number of builds, which are made sequentially.

Signed-off-by: Lukas Holecek <hluk@email.cz>

---

Couple of progress screenshots:

![image](https://user-images.githubusercontent.com/38054/61108889-d4d65c80-a483-11e9-8678-110d99966dc2.png)

![image](https://user-images.githubusercontent.com/38054/61108894-d6a02000-a483-11e9-868b-483208249f0b.png)

![image](https://user-images.githubusercontent.com/38054/61108904-dbfd6a80-a483-11e9-976b-c63964ed961b.png)

2019-07-12 07:49 UTC, pypingou commented on bodhi/server/templates/update.html
> +                console.debug(data);
Do we want to keep this one?

2019-07-12 07:52 UTC, hluk commented on bodhi/server/templates/update.html
> +                console.debug(data);
Ooops, nope. Removing.

2019-07-12 09:20 UTC, Zlopez requested changes
I don't see any tests for the new functionality

2019-07-12 09:27 UTC, cverna commented
As a note Bodhi does also query greenwave from the backend (https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L1968) and the backend code is called for every updates so much more likely to timeout than the frontend.

I think that we should implement this change in backend too.

2019-07-16 06:40 UTC, hluk commented
> I don't see any tests for the new functionality

@Zlopez Are there any browser tests? Couldn't find any, not sure how to write automated tests for this.

2019-07-16 07:27 UTC, Zlopez commented
@hluk Unfortunately not now. As I see you added tests for backends methods, which is everything I wanted from you.

2019-07-16 07:55 UTC, Zlopez approved these changes

2019-07-17 11:58 UTC, hluk commented
@cverna, @pypingou Can you review again please?

2019-07-17 13:54 UTC, Zlopez commented
@hluk `pip-pydocstyle` is failing on this:
```
[2019-07-17T09:53:59.872Z] bodhi/server/models.py:1992 in public method `greenwave_subject_batch_size`:
[2019-07-17T09:53:59.873Z]         D200: One-line docstring should fit on one line with quotes (found 3)
```

2019-07-17 14:02 UTC, hluk commented
> D200: One-line docstring should fit on one line with quotes (found 3)

Oh, OK, thanks - I couldn't find the error in Jenkins job log.

2019-07-17 14:13 UTC, Zlopez commented
Unfortunately still failing:
```
16:10:09  bodhi/server/models.py:1992 in public method `greenwave_subject_batch_size`:
16:10:09          D210: No whitespaces allowed surrounding docstring text
```

2019-07-17 15:25 UTC, merged