Allow to configure a release without an override tag.
fedora-infra/bodhi pull request #3474
Opened 2019-08-19 10:59 UTC by cverna

A few releases do not make use of the buildroot override
(eg container, rawhide, flatpak). This commit makes it possible
to create a release without the override tag.
If an user tries to create a buildroot override for such a release
an error message will be displayed.

Fixes #3447

Signed-off-by: Clement Verna <cverna@tutanota.com>

2019-08-20 09:41 UTC, nphilipp approved these changes
Looks good to me, except the error message string (see below).

2019-08-20 09:41 UTC, nphilipp commented on bodhi/server/validators.py
> +                               " Release associated to build does not support it.")
The error message doesn't read well, how about:

```
"Cannot create a buildroot override because the release associated with the build does not support it."
```

2019-08-20 09:42 UTC, nphilipp requested changes
Oops, missed the one error message string.

2019-08-20 13:24 UTC, cverna commented on bodhi/server/validators.py
> +                               " Release associated to build does not support it.")
Yes that's much better :smile: . I have updated the PR

2019-08-21 08:55 UTC, nphilipp approved these changes
Thanks!

2019-08-21 09:33 UTC, merged