Don't derive test classes from BaseTestCase.
fedora-infra/bodhi pull request #3611
Opened 2019-10-18 11:52 UTC by nphilipp

On the one hand, this still derives from `unittest.TestCase`, which
breaks use of some PyTest features in hard to debug ways. On the other
hand, it also adds unnecessary overhead in form of the test database
that it creates for every called test method.

Signed-off-by: Nils Philippsen <nils@redhat.com>

2019-10-20 23:32 UTC, ryanlerch approved these changes

2019-10-21 09:26 UTC, Zlopez approved these changes

2019-10-28 04:32 UTC, ryanlerch requested changes
Looks like there are 2 self.asserts that i missed in the initial commit on this file, that still worked because i changed them to basetestcase...

https://github.com/fedora-infra/bodhi/pull/3611/files#diff-5d496e504a611a29cbe4cb4888b45c27R298-R301

2019-11-05 08:32 UTC, ryanlerch approved these changes

2019-11-05 09:26 UTC, merged