Migrate test_config.py to pytest
fedora-infra/bodhi pull request #3617
Opened 2019-10-18 19:59 UTC by dimitraz

Removed dependency on unittest.TestCase.
Fixes: https://github.com/fedora-infra/bodhi/issues/3593

Signed-off-by: dimitraz <dzuccare@redhat.com>

2019-10-21 00:56 UTC, ryanlerch approved these changes
LGTM! Thanks!

2019-10-23 15:53 UTC, nphilipp submitted a review, later dismissed
Sorry for not documenting this in the issue -- I only noticed it now -- but for PyTest, the class has to be named "Test<something>". Would you please rename the test classes accordingly? I've added suggestions for each one. Thanks!

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigGetItemTests:
--> "TestBodhiConfigGetItem"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigGetTests:
--> "TestBodhiConfigGet" ...

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigPopItemTests:
--> "TestBodhiConfigPopItem"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigCopyTests:
--> "TestBodhiConfigCopy"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigLoadConfig:
--> "TestBodhiConfigLoad"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigLoadDefaultsTests:
--> "TestBodhiConfigLoadDefaults"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class BodhiConfigValidate:
--> "TestBodhiConfigValidate"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class GenerateListValidatorTests:
--> "TestGenerateListValidator"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class ValidateBoolTests:
--> "TestValidateBool"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class ValidateNoneOrTests:
--> "TestValidateNoneOr"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class ValidatePathTests:
--> "TestValidatePath"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class ValidateRstrippedStrTests:
--> "TestValidateRstrippedStr"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class ValidateSecretTests:
--> "TestValidateSecret"

2019-10-23 15:53 UTC, nphilipp commented on bodhi/tests/server/test_config.py
> +class ValidateTLSURL:
--> "TestValidateTLSURL"

2019-10-24 08:09 UTC, dimitraz commented
Hey @nphilipp, oops sorry about that. I'll try get to that as soon as possible!

2019-10-24 08:23 UTC, dimitraz commented
Should be done now

2019-10-28 22:52 UTC, ryanlerch requested changes
Looking good now, thanks for implementing the changes suggested by @nphilipp !

However, your second commit now does not have the signed off line, which is making the checks fail. Would you be able to squash your two commits into one (and make sure this has the signed-off-by line too)

Additionally, the pip-flake8 check is failing on a few style issues that need to be fixed:

```
[2019-10-28T23:06:40.852Z] ./bodhi/tests/server/test_config.py:20:1: I100 Import statements are in the wrong order. 'from unittest import mock' should be before 'import pytest' and in a different group.
[2019-10-28T23:06:40.852Z] from unittest import mock
[2019-10-28T23:06:40.852Z] ^
[2019-10-28T23:06:40.852Z] ./bodhi/tests/server/test_config.py:20:1: I201 Missing newline between import groups. 'from unittest import mock' is identified as Stdlib and 'import pytest' is identified as Third Party.
[2019-10-28T23:06:40.852Z] from unittest import mock
[2019-10-28T23:06:40.852Z] ^
[2019-10-28T23:06:40.852Z] ./bodhi/tests/server/test_config.py:21:1: I201 Missing newline between import groups. 'from bodhi.server import config' is identified as Application and 'from unittest import mock' is identified as Stdlib.
[2019-10-28T23:06:40.852Z] from bodhi.server import config
[2019-10-28T23:06:40.852Z] ^
[2019-10-28T23:06:40.852Z] ./bodhi/tests/server/test_config.py:162:32: W504 line break after binary operator
[2019-10-28T23:06:40.852Z]         assert (str(exc.value) ==
[2019-10-28T23:06:40.852Z]                                ^
[2019-10-28T23:06:40.852Z] ./bodhi/tests/server/test_config.py:163:13: E128 continuation line under-indented for visual indent
[2019-10-28T23:06:40.852Z]             ('Invalid config values were set: \n\tauthtkt.secure: "not a bool" cannot be '
[2019-10-28T23:06:40.852Z]             ^
[2019-10-28T23:06:40.852Z] ./bodhi/tests/server/test_config.py:300:48: W291 trailing whitespace
[2019-10-28T23:06:40.852Z]         assert not config._validate_bool(False) 
```

cheers!

2019-11-05 09:23 UTC, dimitraz commented
@ryanlerch Sorry about that, I completely forgot to get round to your comment. Is there anything else you need me to do or is that done now?

2019-11-05 09:51 UTC, ryanlerch approved these changes

2019-11-05 09:52 UTC, ryanlerch commented
> @ryanlerch Sorry about that, I completely forgot to get round to your comment. Is there anything else you need me to do or is that done now?

@dimitraz No problems! I fixed the handful of issues, so after the tests pass, it should be right to be merged! Thanks!

2019-11-06 06:59 UTC, merged