set update.pushed to true when moved to testing in the signed consumer
fedora-infra/bodhi pull request #3628
Opened 2019-10-22 13:23 UTC by StephenCoady

Added build.update.pushed = True for the signed consumer so that it can be unpushed. See https://github.com/fedora-infra/bodhi/issues/3625

Signed-off-by: Stephen Coady <scoady@redhat.com>

2019-10-22 17:23 UTC, cverna reviewed
Looks great :-) could you just adjust one of the test to make sure that we check that the boolean is correctly set.

2019-10-23 08:38 UTC, Zlopez requested changes
Could you add news file. See https://github.com/fedora-infra/bodhi/blob/develop/docs/developer/index.rst#release-notes

2019-10-23 12:06 UTC, cverna approved these changes
:+1: thanks

2019-10-23 12:41 UTC, Zlopez approved these changes

2019-10-23 12:44 UTC, merged