Web UI for triggering tests for update
fedora-infra/bodhi pull request #3722
Opened 2019-11-14 09:31 UTC by AdamSaleh

Added a simple modal in UI to trigger update_trigger_tests, so that u…sers can rerun tests in ui.

Signed-off-by: Adam Saleh <asaleh@redhat.com>

2019-11-14 16:44 UTC, sebwoj requested changes

2019-11-14 16:44 UTC, sebwoj commented on bodhi/server/util.py
> +        bool: Indicating if the test results can be waived on the given update.
Let's change this description to reflect real meaning of return value.

2019-11-14 16:44 UTC, sebwoj commented on bodhi/server/templates/update.html
> +% if self.util.can_trigger_tests(update):
Instead of creating additional function, we can use:
`if request.registry.settings.get('test_gating.required')`

2020-01-06 14:17 UTC, StephenCoady approved these changes

2020-01-06 14:18 UTC, merged