WebUI: Make Test Cases look clickable.
fedora-infra/bodhi pull request #4009
Opened 2020-04-22 10:46 UTC by richardgreg

Fixes: #4003

Signed-off-by: Richard O. Gregory <richardgrecoson@gmail.com>

2020-04-22 10:49 UTC, richardgreg commented
The original author intentionally made it 'not blue'. I wonder why though?

2020-04-23 13:58 UTC, mattiaverga requested changes
> The original author intentionally made it 'not blue'. I wonder why though?

I suppose that's because light blue text + small font size + white background is not the best for readability... I would suggest to change the `notblue` class with `font-weight-bolder` to enhance the readability.

Also, let's use f-strings while editing the text.

2020-04-28 15:51 UTC, mattiaverga requested changes

2020-04-28 15:51 UTC, mattiaverga commented on news/4003.dev
> +Make Test Cases look clickable.
Ah, sorry, I didn't notice in my previous review the news fragment type: this isn't a development related change, a filename suffix of `.bug` should be fine.

2020-04-29 05:45 UTC, cverna approved these changes
LGTM

2020-04-29 15:30 UTC, mattiaverga approved these changes

2020-04-29 15:31 UTC, merged