[WIP] Querying Updates using arguments
fedora-infra/bodhi pull request #4086
Opened 2020-07-19 11:12 UTC by karmadolkar

Returns null on the GraphiQL client as of now. Uses `stable_karma`, `unstable_karma`, `stable_days`, `status`, `request`, `pushed`, `critpath`, `date_approved`, `alias`, and `user_id` as arguments to Query.

Signed-off-by: Karma Dolkar <karmadolkar29@gmail.com>

2020-07-20 12:20 UTC, cverna commented on bodhi/server/services/graphql.py
> +    def resolve_getUpdates(self, info, **args):
```suggestion
    def resolve_getUpdate(self, info, **args):
```

2020-07-27 11:58 UTC, StephenCoady commented
This looks good to me so far. You still need to rename the resolver as suggested above though. Also, I think you have linting issues.

As a side note, we may need to move some of this logic to separate files. I think its fine for now but as soon as we add a couple more resolvers then the file is going to become pretty difficult to follow. Maybe we could nest everything under a `services/graphql/` folder. 

Also, the way you had to do types is fine, I suspect its because `type` is a built in function in python.

2020-07-29 10:25 UTC, StephenCoady requested changes
Almost there! Sorry to be difficult, and I realise I was the one to suggest the name in the first place, but could we make `getRelease` and `getUpdate` plural? so `getReleases` etc. I think its more descriptive since its possible to get back multiple releases and updates.

Other than that I'm happy and will approve :+1:

2020-07-30 11:40 UTC, StephenCoady approved these changes
looks good to me!

2020-08-06 10:57 UTC, merged