Avoid daily increment of <updated_date>
fedora-infra/bodhi pull request #4190
Opened 2021-03-11 01:16 UTC by dralley

When writing out the "updated_date" field in the metadata, if the update
has never been modified in Bodhi, rather than using utcnow(), fall back
to using issued_date. This avoids constant churn of the "updated_date".

closes #4189

2021-03-11 14:31 UTC, dralley commented
This fixes some strange behavior described in the linked issue, where most (but not all) of the UpdateInfo in Fedora and CentOS had a constantly-changing <updated_date>. 

This is because ```rec.updated_date``` was set to ```update.date_modified```, or ```datetime.utcnow()``` if it did not exist -- and it doesn't exist for any updates which haven't been manually edited since being pushed, as ```update.date_modified``` is set to ```null``` by default.

2021-03-11 17:01 UTC, mattiaverga requested changes
It seems odd the the relevant test doesn't fail after your changes:
https://github.com/fedora-infra/bodhi/blob/31bfc2ee62b8e96f2eaa8f4553f502caf28ed3ac/bodhi/tests/server/test_metadata.py#L127-L142

Can you have a look at it and change it in accordance with the new behavior?
Also, I'm wondering if we shouldn't set `rec.updated_date` to `update_date_submitted` instead of `date_pushed`... what do you think?

Don't forget to add a new file as explained [here](https://bodhi.fedoraproject.org/docs/developer/#release-notes)

2021-03-11 20:47 UTC, dralley commented
@mattiaverga If ```date_submitted``` can always be expected to be there (unlike ```date_pushed``` as per the inline comment here), then it might make more sense.  However, I'm not a regular user or developer of Bodhi so my opinion is not worth much!

https://github.com/fedora-infra/bodhi/pull/4190/files#diff-d8236f709f77c2189f8e6ebc696a39e7aca1a9e6a5522300a7e9adf558deb62cL230-L242

Regarding the test, looking at the code above, it a actually does make sense that it would pass since the test case doesn't initialize ```date_pushed```, which then gets filled in as ```utcnow()```.  And then due to my patch, ```updated_date``` gets the same value - so they both end up filled in by ```utcnow()```.

What I should be done with the test probably depends on the decision we make here so I'll defer to you there.

2021-03-12 22:44 UTC, dralley commented
@mattiaverga Will wait on the ```date_submitted``` decision before messing with the tests

2021-03-14 08:50 UTC, mattiaverga commented
Just my personal opinion, but I think it would make sense to use `date_submitted`. I've double checked and that is always set.

2021-03-14 15:04 UTC, dralley commented
@mattiaverga Regarding the notice here: https://github.com/fedora-infra/bodhi/blob/16b126a04eb69a159aa8ee885b61661ef3467960/bodhi/server/metadata.py#L233-L236

Do you think perhaps we should do the same with ```issued_date``` if ```date_pushed``` is not set?  It would be more deterministic to use "real" dates as much as possible.

2021-03-14 15:14 UTC, dralley commented
I went ahead and added it, I can squash the commits and update the message if you agree

2021-03-15 16:30 UTC, mattiaverga approved these changes

2021-03-15 16:30 UTC, mattiaverga commented
Thanks for looking at this!

2021-03-15 16:30 UTC, merged

2021-03-15 16:40 UTC, dralley commented
@mattiaverga Thank you!

Do you happen to know when this will be deployed live?  Or if not, is there a way I could be notified when it does?  We would like to close the issue in our downstream issue tracker.

2021-03-16 07:12 UTC, mattiaverga commented
> Do you happen to know when this will be deployed live? Or if not, is there a way I could be notified when it does? We would like to close the issue in our downstream issue tracker.

I don't know. There has been no "project leader" here lately, I'm just trying to move things forward.

I'll ask Fedora infrastructure folks if it's ok for me to publish a new Bodhi release with the latest changes, then we will need someone to deploy it on prod. But I think the deployment needs to wait the end of freeze period (not sure about that).

I'll let you know.

2021-05-14 09:46 UTC, mattiaverga commented
@dralley Bodhi 5.7.0 has been deployed yesterday in prod. Let us know any further problem.

2021-05-14 15:31 UTC, dralley commented
@mattiaverga Thank you!