Enable configuring OIDC storage path
fedora-infra/bodhi pull request #4603
Opened 2022-06-27 13:46 UTC by TomasTomecek

I understand the default makes sense for desktop users. For us in Packit, our
`~/.config` is not writable in our deployment as k8s mounts secrets there R/O
so we cannot create new files in `~/.config` (but `$HOME` is fine!).

Thanks to this PR, we'd get rid of this nasty hack in our codebase:
https://github.com/packit/packit/commit/57cf0944788d1854309b85f27a1cd1411b399fc6

2022-07-02 13:07 UTC, mattiaverga requested changes
There are a couple of failures due to flake8 style checks, the Integration Tests failures should go away once you rebase to latest devel.
It would also nice to add a release note as described [here](https://fedora-infra.github.io/bodhi/6.0/developer/index.html#release-notes).

2022-07-13 13:54 UTC, TomasTomecek commented
This slipped b/w my fingers after I returned from my vacation.

fixed and rebased

2022-07-14 07:30 UTC, TomasTomecek commented
The rawhide failure is unrelated:
```
++ git rev-parse --short HEAD
2859
fatal: detected dubious ownership in repository at '/bodhi'
2860
To add an exception for this directory, call:
2861
2862
	git config --global --add safe.directory /bodhi
```
BTW we got bit by that too.

2022-07-14 15:13 UTC, mattiaverga approved these changes
:+1:

2022-07-14 15:29 UTC, merged