Add frequencyupdateinfo.json artifact to release
fedora-infra/bodhi pull request #5172
Opened 2023-03-27 13:27 UTC by RishabhSaini

Detailed rationale in:
https://github.com/coreos/rpm-ostree/issues/4247#issuecomment-1467819269

2023-04-10 16:10 UTC, mattiaverga requested changes
Some comments inline from a quick look.
Also, missing tests and release notes file.

2023-04-10 16:10 UTC, mattiaverga commented on bodhi-server/bodhi/server/metadata.py
> +            ])
I don't think this is needed, as the previous filter is against `release.id`.

2023-04-10 16:10 UTC, mattiaverga commented on bodhi-server/bodhi/server/metadata.py
> +            update.id.asc()
I think it is best to order by `date_submitted`

2023-04-10 16:10 UTC, mattiaverga commented on bodhi-server/bodhi/server/metadata.py
> +                simplified_update["builds"].push(simplified_build)
`"builds" : [{"nvr_name" : build.nvr_name()} for build in update.builds]`

And missing commas between dict elements.

2023-04-10 16:10 UTC, mattiaverga commented on bodhi-server/bodhi/server/metadata.py
> +        self.zchunk = True
Could we share settings with UpdateInfoMetadata?
Otherwise we should copy them (AFAIK, zchunk is disabled for EPEL releases as it won't work)

2023-04-10 16:10 UTC, mattiaverga commented on bodhi-server/bodhi/server/models.py
> +    frequencyupdateinfo = 'frequencyupdateinfo', 'Generating frequency update info'
This will need a database migration file, I think.

2023-04-17 17:18 UTC, RishabhSaini commented
Closing due to: https://github.com/coreos/rpm-ostree/issues/4247#issuecomment-1511759881

2023-04-17 17:18 UTC, closed without merging