Send fedmsg notifications during ostree composes
fedora-infra/bodhi pull request #931
Opened 2016-09-15 12:48 UTC by puiterwijk

This also uses the ref and commitid returned by fedmsg-atomic-composer#7.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2016-09-15 17:25 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +                notifications.publish(topic="ostree.start",
Should this be ostree.failed or something?

2016-09-15 17:26 UTC, puiterwijk commented on bodhi/server/consumers/masher.py
> +                notifications.publish(topic="ostree.start",
Haha, yes. That had been my intention.

2016-09-15 17:47 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +                                      force=True)
Maybe we could rewrap the above so it's a little cleaner, like

```
                notifications.publish(
                    topic="ostree.compose.finish",
                    msg=dict(
                        tag=tag,
                        ref=result.get('ref'),
                        commitid=result.get('commitid')),
                    force=True)
```

You can leave it as-is if you prefer, just a suggestion.

2016-09-15 22:30 UTC, puiterwijk commented on bodhi/server/consumers/masher.py
> +                                      force=True)
Done

2016-09-16 17:04 UTC, bowlofeggs commented on bodhi/server/consumers/masher.py
> +                     force=True)
It looks like this ```force``` isn't lined up with the ```msg``` above it, maybe one too many spaces?

2016-09-16 17:06 UTC, bowlofeggs requested changes
Two things to fix before merging:
1. Let's fix that indentation on `force`.
2. Since it is programmatically important that these messages get sent correctly for signing to work with it, we should add two tests to ensure they do get sent during mash. One test for the success case, and the other for the failure case.

2016-09-18 16:12 UTC, pypingou commented on bodhi/server/consumers/masher.py
> +                notifications.publish(topic="ostree.start",
though a little risky, we could make it something like ``topic="ostree.%s" % result['result']`` no?

Risky as in: for every new result, we'll need to adjust fedmsg_meta.

2016-09-24 02:43 UTC, puiterwijk commented on bodhi/server/consumers/masher.py
> +                notifications.publish(topic="ostree.start",
I would prefer just keeping with the ==success !=success cases, as those are the only two that the atomic composer is aware of.

2016-09-27 18:49 UTC, bowlofeggs commented
Since @puiterwijk has been so helpful to me over the past week, I'm going to attempt to write the tests for him in a separate pull request and I'll merge this now. Thanks @puiterwijk!

2016-09-27 18:49 UTC, merged